package at.koopro.wizardsandbeasts.client.armor;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import org.junit.jupiter.api.Test;
import at.koopro.wizardsandbeasts.registry.ArmorItemRegistry;
import software.bernie.geckolib.renderer.GeoArmorRenderer;

import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * That the GeckoLib armour assets are loadable, correctly boned and actually modelled.
 *
 * <p>These files are the failure the wardrobe is most exposed to. A worn piece with no
 * {@code .geo.json} behind it does not degrade to the vanilla layer — GeckoLib throws while the
 * armour layer is drawing, which means a crash the first time anybody equips a robe, on a path no
 * headless test reaches. Parsing them here is the cheap half of that check.
 *
 * <p>All of it is generated by {@code tools/armor_model.py}, which packs the UV islands and paints
 * the sheet through the same rectangles — so geometry and texture cannot disagree <em>within</em> a
 * run. What they can do is drift between runs, if a model is hand-edited afterwards and the sheet
 * is not. That is what the size and cube-count assertions are for.
 *
 * <p>The bone names are the other half, and they fail in the opposite direction: {@code
 * GeoArmorRenderer} resolves a segment to a bone by name and <em>drops an unknown bone silently</em>.
 * A typo'd {@code armorBody} is not an error, just a robe that never appears. Only an explicit list
 * catches that.
 */
class ArmorGeoAssetTest {

    private static final Path MODELS =
            Path.of("src", "main", "resources", "assets", "wizards_and_beasts", "geckolib", "models", "armor");
    private static final Path ANIMATIONS =
            Path.of("src", "main", "resources", "assets", "wizards_and_beasts", "geckolib", "animations", "armor");
    private static final Path TEXTURES =
            Path.of("src", "main", "resources", "assets", "wizards_and_beasts", "textures", "armor");

    /**
     * Every bone name {@code GeoArmorRenderer#getBoneNameForSegment} can ask for.
     *
     * <p>Hand-listed because that method is an instance method needing a render state, so the names
     * cannot be enumerated from GeckoLib directly. {@link #theBoneVocabularyStillMatchesGeckolib()}
     * guards the copy against GeckoLib growing a segment under it.
     */
    private static final Set<String> ARMOR_BONES = Set.of(
            "armorHead", "armorBody", "armorLeftArm", "armorRightArm",
            "armorLeftLeg", "armorRightLeg", "armorLeftBoot", "armorRightBoot");

    /** Sets drawn on the body: chest, legs and boots all come out of one file. */
    private static final List<String> BODY_SETS = List.of("student_robe", "auror_robe", "death_eater_robe");

    /** Sets that only ever occupy the head slot. */
    private static final List<String> HEAD_SETS = List.of("wizard_hat", "death_eater_mask");

    @Test
    void theBoneVocabularyStillMatchesGeckolib() {
        assertEquals(GeoArmorRenderer.ArmorSegment.values().length, ARMOR_BONES.size(),
                "GeckoLib changed its armor segments — re-check getBoneNameForSegment and update ARMOR_BONES");
    }

    @Test
    void everySetShipsAModelThatParses() throws IOException {
        for (String set : allSets()) {
            JsonObject model = readJson(MODELS.resolve(set + ".geo.json"));
            assertTrue(model.has("format_version"), set + " has no format_version");
            JsonArray geometry = model.getAsJsonArray("minecraft:geometry");
            assertEquals(1, geometry.size(), set + " should hold exactly one geometry");
        }
    }

    @Test
    void everySetShipsAnAnimationFileThatParses() throws IOException {
        for (String set : allSets()) {
            JsonObject animations = readJson(ANIMATIONS.resolve(set + ".animation.json"));
            assertTrue(animations.has("format_version"), set + " has no format_version");
            assertTrue(animations.has("animations"), set + " has no animations object");
        }
    }

    @Test
    void noModelCarriesARootBoneGeckolibWillNeverAskFor() throws IOException {
        // A *root* bone has to be one of the eight, because GeoArmorRenderer finds bones by name
        // and drops an unknown one without a word. A bone with a parent is a different case: the
        // drape bones (robeSkirt, robeHem, robeHood) are never looked up, they ride along with
        // whichever armour bone they hang from, and exist so a controller can animate the cloth.
        for (String set : allSets()) {
            for (var element : bonesArray(set)) {
                JsonObject bone = element.getAsJsonObject();
                if (bone.has("parent")) {
                    continue;
                }
                String name = bone.get("name").getAsString();
                assertTrue(ARMOR_BONES.contains(name),
                        set + " has root bone '" + name + "', which GeoArmorRenderer drops silently");
            }
        }
    }

    @Test
    void everyChildBoneHangsFromABoneThatExists() throws IOException {
        // A parent named but not declared is the same silent drop by another route.
        for (String set : allSets()) {
            Set<String> declared = bonesOf(set);
            for (var element : bonesArray(set)) {
                JsonObject bone = element.getAsJsonObject();
                if (!bone.has("parent")) {
                    continue;
                }
                String parent = bone.get("parent").getAsString();
                assertTrue(declared.contains(parent),
                        set + ": bone '" + bone.get("name").getAsString()
                                + "' hangs from '" + parent + "', which is not declared");
            }
        }
    }

    @Test
    void bodySetsCoverEverySlotTheirPiecesOccupy() throws IOException {
        // The chest item draws body + both arms, the legs item both legs, the boots item both feet.
        // A set missing one of these renders that piece as nothing at all.
        for (String set : BODY_SETS) {
            Set<String> bones = bonesOf(set);
            for (String required : List.of("armorBody", "armorLeftArm", "armorRightArm",
                    "armorLeftLeg", "armorRightLeg", "armorLeftBoot", "armorRightBoot")) {
                assertTrue(bones.contains(required), set + " is missing " + required);
            }
        }
    }

    @Test
    void headSetsCarryTheHeadBone() throws IOException {
        for (String set : HEAD_SETS) {
            assertTrue(bonesOf(set).contains("armorHead"), set + " is missing armorHead");
        }
    }

    @Test
    void everySetHasActualGeometry() throws IOException {
        // The first cut of these files declared the right bones and not one cube. That is not a
        // failure any renderer reports: the piece equips, grants its stats and draws nothing.
        for (String set : allSets()) {
            int cubes = 0;
            for (var bone : bonesArray(set)) {
                var array = bone.getAsJsonObject().getAsJsonArray("cubes");
                cubes += array == null ? 0 : array.size();
            }
            assertTrue(cubes > 0, set + " declares bones but no cubes — it would draw nothing");
        }
    }

    @Test
    void everyModelAgreesWithItsTextureSize() throws IOException {
        // Box UV is resolved against the sizes in the model's description, not against the PNG.
        // If the two drift the sheet is sampled at the wrong scale and every face tears — with
        // no error anywhere, because neither file is individually wrong.
        for (String set : allSets()) {
            var description = readJson(MODELS.resolve(set + ".geo.json"))
                    .getAsJsonArray("minecraft:geometry")
                    .get(0).getAsJsonObject()
                    .getAsJsonObject("description");
            Path png = TEXTURES.resolve(set + ".png");
            assertTrue(Files.exists(png), "missing texture: " + png);
            BufferedImage image = ImageIO.read(png.toFile());
            assertEquals(image.getWidth(), description.get("texture_width").getAsInt(),
                    set + " texture_width disagrees with " + png);
            assertEquals(image.getHeight(), description.get("texture_height").getAsInt(),
                    set + " texture_height disagrees with " + png);
        }
    }

    @Test
    void everyMaskCastingShipsItsOwnTexture() {
        // The six castings share one model, so a missing PNG is not a missing model — the mask
        // just renders with the missing-texture checkerboard on its face.
        for (int variant = 0; variant <= 5; variant++) {
            Path png = TEXTURES.resolve(DeathEaterMaskRenderer.textureName(variant) + ".png");
            assertTrue(Files.exists(png), "missing casting texture: " + png);
        }
    }

    @Test
    void everyWornArmourItemHasAnInventorySprite() {
        // The gap this test exists for: the whole set shipped with worn models, worn textures
        // and no item icon whatsoever. It rendered correctly on the body and was a missing
        // model in the hotbar, which no other assertion here would have noticed.
        Path sprites = Path.of("src", "main", "resources", "assets", "wizards_and_beasts",
                "textures", "item");
        List<String> missing = new ArrayList<>();
        for (var piece : ArmorItemRegistry.ALL) {
            String id = piece.getId().getPath();
            if (!Files.exists(sprites.resolve(id + ".png"))) {
                missing.add(id);
            }
        }
        assertTrue(missing.isEmpty(), "worn armour with no inventory sprite: " + missing);
    }

    // -- variant wiring ------------------------------------------------------------------------

    @Test
    void maskTextureNamesMatchTheRegisteredItemIds() {
        // The renderer is built per item, so a mismatch here is a mask wearing the wrong face with
        // nothing to report it. These are the ids in ArmorItemRegistry.
        assertEquals("death_eater_mask", DeathEaterMaskRenderer.textureName(0));
        for (int variant = 1; variant <= 5; variant++) {
            assertEquals("death_eater_mask_" + variant, DeathEaterMaskRenderer.textureName(variant));
        }
    }

    @Test
    void everyMaskCastingResolvesToItsOwnTexture() {
        Set<String> names = new LinkedHashSet<>();
        for (int variant = 0; variant <= 5; variant++) {
            names.add(DeathEaterMaskRenderer.textureName(variant));
        }
        assertEquals(6, names.size(), "two castings would share a texture");
    }

    // -- helpers -------------------------------------------------------------------------------

    private static List<String> allSets() {
        return java.util.stream.Stream.concat(BODY_SETS.stream(), HEAD_SETS.stream()).toList();
    }

    private static JsonArray bonesArray(String set) throws IOException {
        return readJson(MODELS.resolve(set + ".geo.json"))
                .getAsJsonArray("minecraft:geometry")
                .get(0).getAsJsonObject()
                .getAsJsonArray("bones");
    }

    private static Set<String> bonesOf(String set) throws IOException {
        JsonArray bones = bonesArray(set);
        Set<String> names = new LinkedHashSet<>();
        bones.forEach(bone -> names.add(bone.getAsJsonObject().get("name").getAsString()));
        assertFalse(names.isEmpty(), set + " declares no bones");
        return names;
    }

    private static JsonObject readJson(Path path) throws IOException {
        assertTrue(Files.exists(path), "missing asset: " + path);
        return JsonParser.parseString(Files.readString(path)).getAsJsonObject();
    }
}
