package at.koopro.wizardsandbeasts.client.skill.gui;

import at.koopro.wizardsandbeasts.client.gui.WizardsPalette.GuiSkin;
import at.koopro.wizardsandbeasts.client.gui.util.UiContrast;
import at.koopro.wizardsandbeasts.WizardsAndBeastsMod;
import at.koopro.wizardsandbeasts.skill.Skill;
import at.koopro.wizardsandbeasts.skill.SkillTreeId;
import net.minecraft.resources.Identifier;

import java.util.EnumMap;
import java.util.Map;

/**
 * The skill web's sprite set and palette.
 *
 * <p>PNGs are generated by {@code tools/skill_chart_textures.py} (deterministic, regenerable) and
 * committed under {@code textures/gui/skill_tree/chart/}. The chart is a page of an engraved star
 * atlas: blue-grey vellum, indigo ink, silver leaf. The star sprites are authored white and inked
 * here at draw time, so one {@code star_core_notable.png} serves as the silver roundel under a taken
 * star and as the vellum knockout that stops lines short of an untaken one. The page layers, the
 * points bar and the control icons carry their own colour and are drawn {@link #UNTINTED}.
 *
 * <p>Colours come from the {@code star_chart} skin ({@link GuiSkin#STAR_CHART}); the few the enum
 * has no accessor for are spelled here with the skin generator's name for them.
 */
public final class SkillTreeChartTextures {

    private SkillTreeChartTextures() {}

    // ── Page layers, back to front ─────────────────────────────────────────
    //
    // The file names are the night sky's; the art is the atlas page. `STARFIELD_FAR` is the
    // opaque vellum with its dotted graticule, `NEBULA` the stippled Milky Way and `STARFIELD`
    // the uncatalogued background stars, both on alpha. All three are printed on one sheet, so
    // SkillTreeScreen moves them together with the chart.

    public static final int STARFIELD_SIZE = 512;
    public static final int NEBULA_SIZE = 256;
    public static final int VIGNETTE_SIZE = 64;

    public static final Identifier STARFIELD_FAR = tex("starfield_far");
    public static final Identifier NEBULA = tex("nebula");
    public static final Identifier STARFIELD = tex("starfield");
    /** Faint edge toning over the viewport contents, inside the scissor. */
    public static final Identifier VIGNETTE = tex("vignette");

    // ── Geometry that used to be drawn primitives ──────────────────────────

    /** A graduated circle, stretched to each survey radius. Replaced a midpoint-circle of fills. */
    public static final Identifier SURVEY_RING = tex("survey_ring");

    /**
     * Line strip, rotated onto each connection (or each dash of one). A crisp engraved stroke,
     * uniform along its length; the dash patterns are laid by the screen.
     */
    public static final Identifier LEY_LINE = tex("ley_line");
    public static final int LEY_LINE_W = 16;
    public static final int LEY_LINE_H = 8;

    // ── Nodes ──────────────────────────────────────────────────────────────

    public static final Identifier STAR_POLARIS = tex("star_polaris");
    /** A soft wash: hover cue, allocatable pulse and region washes, told apart by scale and alpha. */
    public static final Identifier STAR_HALO = tex("star_halo");

    private static final Map<Skill.Size, Identifier> CORE = new EnumMap<>(Skill.Size.class);
    private static final Map<Skill.Size, Identifier> RING = new EnumMap<>(Skill.Size.class);
    private static final Map<Skill.Size, Identifier> FLARE = new EnumMap<>(Skill.Size.class);
    private static final Map<Skill.Size, Identifier> LOCKED = new EnumMap<>(Skill.Size.class);

    static {
        for (Skill.Size size : Skill.Size.values()) {
            String suffix = size.getSerializedName();
            CORE.put(size, tex("star_core_" + suffix));
            RING.put(size, tex("star_ring_" + suffix));
            FLARE.put(size, tex("star_flare_" + suffix));
            LOCKED.put(size, tex("star_locked_" + suffix));
        }
    }

    /** A plain disc: the vellum knockout under an untaken star, the silver roundel under a taken one. */
    public static Identifier core(Skill.Size size) { return CORE.get(size); }
    public static Identifier ring(Skill.Size size) { return RING.get(size); }
    public static Identifier flare(Skill.Size size) { return FLARE.get(size); }

    /**
     * The uncharted position: a thin open circle.
     *
     * <p>Its own shape, not a faint tint of {@link #ring}. Locked and allocatable used to differ
     * only in brightness, so the one thing a player has to read at a glance -- can I take this
     * yet -- was carried by tint alone, on a canvas where every star is tinted something.
     */
    public static Identifier locked(Skill.Size size) { return LOCKED.get(size); }

    // ── Furniture ──────────────────────────────────────────────────────────

    public static final Identifier PIP_ON = tex("pip_on");
    public static final Identifier PIP_OFF = tex("pip_off");

    public static final Identifier BAR_TRACK = tex("bar_track");
    public static final Identifier BAR_FILL = tex("bar_fill");
    public static final int BAR_SPRITE_SIZE = 8;

    public static final Identifier ICON_ZOOM_IN = tex("icon_zoom_in");
    public static final Identifier ICON_ZOOM_OUT = tex("icon_zoom_out");
    public static final Identifier ICON_RECENTER = tex("icon_recenter");
    public static final int ICON_SIZE = 12;

    // ── Palette: the star_chart material ───────────────────────────────────

    /** Indigo ink: body text, taken stars, taken lines. */
    public static final int CHART_INK = GuiSkin.STAR_CHART.ink();
    /** The ink laid thin: labels, secondary text, Polaris before it is taken. */
    public static final int CHART_INK_2 = GuiSkin.STAR_CHART.muted();
    /**
     * Faint ink: uncharted stars and dotted lines only, never text (under AA on the vellum).
     * The skin generator's {@code ink_3}, which {@link GuiSkin} carries no accessor for.
     */
    public static final int CHART_INK_FAINT = 0xFF7C85A6;
    /** Silver leaf: the roundel under a taken star and the underlay of a taken line. */
    public static final int SILVER = GuiSkin.STAR_CHART.accent();
    /** Tarnished silver: the hover wash over a taken star. The generator's {@code gilt_d}. */
    public static final int SILVER_DARK = 0xFF6F7A8C;
    /**
     * The vellum face, for knockouts. Tinting {@link #core} with it lays paper over the lines
     * beneath, the engraver's gap that stops a line short of a star.
     */
    public static final int VELLUM = GuiSkin.STAR_CHART.base();
    /** No tint: the sentinel the tinted blit overload treats as "draw the sprite as authored". */
    public static final int UNTINTED = 0xFFFFFFFF;

    private static final Map<SkillTreeId, Integer> REGION_TINT = new EnumMap<>(SkillTreeId.class);
    private static final Map<SkillTreeId, Identifier> REGION_GLYPH = new EnumMap<>(SkillTreeId.class);

    static {
        // Hand-colouring inks, as a printed atlas was washed after the press: deep enough to draw
        // a ring or a dashed line on the vellum, and laid thin for the region washes. Text in
        // these still goes through UiContrast, since a hue is only a hue.
        REGION_TINT.put(SkillTreeId.HERBOLOGY, 0xFF2F6B3A);
        REGION_TINT.put(SkillTreeId.MAGIZOOLOGY, 0xFF2C5A8A);
        REGION_TINT.put(SkillTreeId.SPELL_MASTERY, 0xFF7A5A14);
        REGION_TINT.put(SkillTreeId.DARK_ARTS, 0xFF7A1F2E);
        REGION_TINT.put(SkillTreeId.ALCHEMY, 0xFF1F6A64);
        REGION_TINT.put(SkillTreeId.WANDLORE, 0xFF7A4A22);
        // Goblin/elf webs: same skin, their own inks (no special-case rendering).
        REGION_TINT.put(SkillTreeId.GOBLIN_CRAFT, 0xFF5A5640);
        REGION_TINT.put(SkillTreeId.ELF_BOND, 0xFF5A3F80);

        // One asterism per region, keyed off the enum's own serialized id so the generator's file
        // names and this map cannot drift.
        for (SkillTreeId tree : SkillTreeId.values()) {
            REGION_GLYPH.put(tree, tex("region_" + tree.getId()));
        }
    }

    public static int regionTint(SkillTreeId tree) {
        return REGION_TINT.getOrDefault(tree, CHART_INK_2);
    }

    /** The region's ink as text on the vellum: its hue, darkened as far as AA contrast needs. */
    public static int regionTextInk(SkillTreeId tree) {
        return UiContrast.readableOn(regionTint(tree), VELLUM);
    }

    /** The region's constellation glyph, drawn beside its label. */
    public static Identifier regionGlyph(SkillTreeId tree) {
        return REGION_GLYPH.get(tree);
    }

    public static final int REGION_GLYPH_SIZE = 16;

    /** Applies an alpha (0-255) to an ARGB color. */
    public static int withAlpha(int argb, int alpha) {
        return (alpha << 24) | (argb & 0xFFFFFF);
    }

    private static Identifier tex(String name) {
        return Identifier.fromNamespaceAndPath(WizardsAndBeastsMod.MODID,
                "textures/gui/skill_tree/chart/" + name + ".png");
    }
}
