package at.koopro.wizardsandbeasts.client.skill.gui;

import at.koopro.wizardsandbeasts.client.gui.WizardsPalette.GuiSkin;
import at.koopro.wizardsandbeasts.WizardsAndBeastsMod;
import at.koopro.wizardsandbeasts.skill.Skill;
import at.koopro.wizardsandbeasts.skill.SkillTreeId;
import net.minecraft.resources.Identifier;

import java.util.EnumMap;
import java.util.Map;

/**
 * The skill web's sprite set and palette.
 *
 * <p>PNGs are generated by {@code tools/skill_chart_textures.py} (deterministic, regenerable) and
 * committed under {@code textures/gui/skill_tree/chart/}. Everything except the four backdrop
 * pieces is authored white or greyscale and coloured here at draw time, so one
 * {@code star_core_notable.png} serves gold-when-allocated, region-tinted-when-allocatable and
 * dim-ember-when-locked.
 *
 * <p>This is also where the night palette lives. {@link at.koopro.wizardsandbeasts.client.gui.WizardsPalette}
 * is scoped to the mod's leather-and-brass chrome and carries no night values; the chart is the one
 * screen that needs them.
 */
public final class SkillTreeChartTextures {

    private SkillTreeChartTextures() {}

    // ── Backdrop, back to front ────────────────────────────────────────────
    //
    // Three depths rather than one tile. `STARFIELD_FAR` is opaque and is the bottom of the
    // stack; the other two carry alpha and are composed over it. What sells the depth is not the
    // art but the difference in how far each travels -- see the parallax factors in
    // SkillTreeScreen.

    public static final int STARFIELD_SIZE = 512;
    public static final int NEBULA_SIZE = 256;
    public static final int VIGNETTE_SIZE = 64;

    public static final Identifier STARFIELD_FAR = tex("starfield_far");
    public static final Identifier NEBULA = tex("nebula");
    public static final Identifier STARFIELD = tex("starfield");
    /** Edge darkening over the viewport contents, inside the scissor. */
    public static final Identifier VIGNETTE = tex("vignette");

    // ── Geometry that used to be drawn primitives ──────────────────────────

    /** One faint circle, stretched to each survey radius. Replaced a midpoint-circle of fills. */
    public static final Identifier SURVEY_RING = tex("survey_ring");

    /** Edge strip, rotated onto each connection. Replaced a Bresenham run of fills. */
    public static final Identifier LEY_LINE = tex("ley_line");
    public static final int LEY_LINE_W = 16;
    public static final int LEY_LINE_H = 8;

    // ── Nodes ──────────────────────────────────────────────────────────────

    public static final Identifier STAR_POLARIS = tex("star_polaris");
    /** Wide soft glow: hover ring and allocatable pulse, told apart by scale and alpha. */
    public static final Identifier STAR_HALO = tex("star_halo");

    private static final Map<Skill.Size, Identifier> CORE = new EnumMap<>(Skill.Size.class);
    private static final Map<Skill.Size, Identifier> RING = new EnumMap<>(Skill.Size.class);
    private static final Map<Skill.Size, Identifier> FLARE = new EnumMap<>(Skill.Size.class);
    private static final Map<Skill.Size, Identifier> LOCKED = new EnumMap<>(Skill.Size.class);

    static {
        for (Skill.Size size : Skill.Size.values()) {
            String suffix = size.getSerializedName();
            CORE.put(size, tex("star_core_" + suffix));
            RING.put(size, tex("star_ring_" + suffix));
            FLARE.put(size, tex("star_flare_" + suffix));
            LOCKED.put(size, tex("star_locked_" + suffix));
        }
    }

    public static Identifier core(Skill.Size size) { return CORE.get(size); }
    public static Identifier ring(Skill.Size size) { return RING.get(size); }
    public static Identifier flare(Skill.Size size) { return FLARE.get(size); }

    /**
     * The unlit socket.
     *
     * <p>Its own shape, not a dim tint of {@link #core}. Locked and allocatable used to differ
     * only in brightness, so the one thing a player has to read at a glance -- can I take this
     * yet -- was carried by tint alone, on a canvas where every star is tinted something.
     */
    public static Identifier locked(Skill.Size size) { return LOCKED.get(size); }

    // ── Furniture ──────────────────────────────────────────────────────────

    public static final Identifier PIP_ON = tex("pip_on");
    public static final Identifier PIP_OFF = tex("pip_off");

    public static final Identifier BAR_TRACK = tex("bar_track");
    public static final Identifier BAR_FILL = tex("bar_fill");
    public static final int BAR_SPRITE_SIZE = 8;

    public static final Identifier ICON_ZOOM_IN = tex("icon_zoom_in");
    public static final Identifier ICON_ZOOM_OUT = tex("icon_zoom_out");
    public static final Identifier ICON_RECENTER = tex("icon_recenter");
    public static final int ICON_SIZE = 12;

    // ── Palette (locked design direction) ──────────────────────────────────

    /** Gold — allocated nodes/edges; overrides region tint. */
    public static final int GOLD = 0xFFE8C76A;
    /** Dim ember — locked stars (brightness cue lives in the tint, shape cue in the sprite). */
    public static final int EMBER = 0xFF6E6156;
    /** Locked edge hairline: faint blue-grey. */
    public static final int EDGE_LOCKED = 0xFF272E44;
    /**
     * Secondary text on the night plate.
     *
     * <p>Deliberately <em>not</em> {@code GuiSkin.STAR_CHART.muted()}, which is a saturated blue
     * ({@code #7FA6D8}) the art uses for its own furniture. This is the greyer voice that reads as
     * disabled next to {@link #CHART_INK}; the two are different colours doing different jobs, so
     * folding them would be a change, not a de-duplication.
     */
    public static final int NIGHT_TEXT_DIM = 0xFF8C93AA;
    /**
     * The {@code star_chart} skin's own silver ink, for label text and the untinted furniture.
     *
     * <p>The deep-night fill colours that used to live here went with the {@code fill()} calls
     * that consumed them: the footer strip and the tooltip card are sprites now, and a colour
     * constant nothing paints with is a knob waiting to drift out of step with the art.
     */
    public static final int CHART_INK = GuiSkin.STAR_CHART.ink();
    /** No tint: the sentinel the tinted blit overload treats as "draw the sprite as authored". */
    public static final int UNTINTED = 0xFFFFFFFF;

    private static final Map<SkillTreeId, Integer> REGION_TINT = new EnumMap<>(SkillTreeId.class);
    private static final Map<SkillTreeId, Identifier> REGION_GLYPH = new EnumMap<>(SkillTreeId.class);

    static {
        REGION_TINT.put(SkillTreeId.HERBOLOGY, 0xFF8FD0A0);
        REGION_TINT.put(SkillTreeId.MAGIZOOLOGY, 0xFF9FC4E8);
        REGION_TINT.put(SkillTreeId.SPELL_MASTERY, 0xFFF0E2B0);
        REGION_TINT.put(SkillTreeId.DARK_ARTS, 0xFFC96F7F);
        REGION_TINT.put(SkillTreeId.ALCHEMY, 0xFF8FD8CF);
        REGION_TINT.put(SkillTreeId.WANDLORE, 0xFFD9B48F);
        // Goblin/elf webs: same skin, neutral silver tint (no special-case rendering).
        REGION_TINT.put(SkillTreeId.GOBLIN_CRAFT, 0xFFC9C2A8);
        REGION_TINT.put(SkillTreeId.ELF_BOND, 0xFFC0AED6);

        // One asterism per region, keyed off the enum's own serialized id so the generator's file
        // names and this map cannot drift.
        for (SkillTreeId tree : SkillTreeId.values()) {
            REGION_GLYPH.put(tree, tex("region_" + tree.getId()));
        }
    }

    public static int regionTint(SkillTreeId tree) {
        return REGION_TINT.getOrDefault(tree, 0xFFB8C0D8);
    }

    /** The region's constellation glyph, drawn beside its label. */
    public static Identifier regionGlyph(SkillTreeId tree) {
        return REGION_GLYPH.get(tree);
    }

    public static final int REGION_GLYPH_SIZE = 16;

    /** Applies an alpha (0-255) to an ARGB color. */
    public static int withAlpha(int argb, int alpha) {
        return (alpha << 24) | (argb & 0xFFFFFF);
    }

    private static Identifier tex(String name) {
        return Identifier.fromNamespaceAndPath(WizardsAndBeastsMod.MODID,
                "textures/gui/skill_tree/chart/" + name + ".png");
    }
}
