package at.koopro.wizardsandbeasts.client.skill.gui;

import at.koopro.wizardsandbeasts.WizardsAndBeastsMod;
import at.koopro.wizardsandbeasts.skill.Skill;
import at.koopro.wizardsandbeasts.skill.SkillTreeId;
import net.minecraft.resources.Identifier;

import java.util.EnumMap;
import java.util.Map;

/**
 * Star-chart sprite set + palette for the skill web canvas (web rework Phase 5).
 * PNGs are generated by {@code tools/skill_chart_textures.py} (deterministic; regenerable) and
 * committed under {@code textures/gui/skill_tree/chart/}. Sprites are white/grayscale and tinted
 * at draw time via the color-blit overload.
 */
public final class SkillTreeChartTextures {

    private SkillTreeChartTextures() {}

    public static final int STARFIELD_SIZE = 512;
    public static final Identifier STARFIELD = tex("starfield");
    public static final Identifier STAR_POLARIS = tex("star_polaris");

    private static final Map<Skill.Size, Identifier> CORE = new EnumMap<>(Skill.Size.class);
    private static final Map<Skill.Size, Identifier> RING = new EnumMap<>(Skill.Size.class);
    private static final Map<Skill.Size, Identifier> FLARE = new EnumMap<>(Skill.Size.class);

    static {
        for (Skill.Size size : Skill.Size.values()) {
            String suffix = size.getSerializedName();
            CORE.put(size, tex("star_core_" + suffix));
            RING.put(size, tex("star_ring_" + suffix));
            FLARE.put(size, tex("star_flare_" + suffix));
        }
    }

    public static Identifier core(Skill.Size size) { return CORE.get(size); }
    public static Identifier ring(Skill.Size size) { return RING.get(size); }
    public static Identifier flare(Skill.Size size) { return FLARE.get(size); }

    // ── Palette (locked design direction) ──

    /** Gold — allocated nodes/edges; overrides region tint. */
    public static final int GOLD = 0xFFE8C76A;
    /** Dim ember — locked stars (brightness cue lives in the tint, shape cue in the sprite). */
    public static final int EMBER = 0xFF6E6156;
    /** Locked edge hairline: faint blue-grey. */
    public static final int EDGE_LOCKED = 0xFF272E44;
    /** Deep-night fills (footer strip, tooltip card). */
    public static final int NIGHT_BG = 0xF20A0E1A;
    public static final int NIGHT_TEXT_DIM = 0xFF8C93AA;

    private static final Map<SkillTreeId, Integer> REGION_TINT = new EnumMap<>(SkillTreeId.class);

    static {
        REGION_TINT.put(SkillTreeId.HERBOLOGY, 0xFF8FD0A0);
        REGION_TINT.put(SkillTreeId.MAGIZOOLOGY, 0xFF9FC4E8);
        REGION_TINT.put(SkillTreeId.SPELL_MASTERY, 0xFFF0E2B0);
        REGION_TINT.put(SkillTreeId.DARK_ARTS, 0xFFC96F7F);
        REGION_TINT.put(SkillTreeId.ALCHEMY, 0xFF8FD8CF);
        REGION_TINT.put(SkillTreeId.WANDLORE, 0xFFD9B48F);
        // Goblin/elf webs: same skin, neutral silver tint (no special-case rendering).
        REGION_TINT.put(SkillTreeId.GOBLIN_CRAFT, 0xFFC9C2A8);
        REGION_TINT.put(SkillTreeId.ELF_BOND, 0xFFC0AED6);
    }

    public static int regionTint(SkillTreeId tree) {
        return REGION_TINT.getOrDefault(tree, 0xFFB8C0D8);
    }

    /** Applies an alpha (0-255) to an ARGB color. */
    public static int withAlpha(int argb, int alpha) {
        return (alpha << 24) | (argb & 0xFFFFFF);
    }

    private static Identifier tex(String name) {
        return Identifier.fromNamespaceAndPath(WizardsAndBeastsMod.MODID,
                "textures/gui/skill_tree/chart/" + name + ".png");
    }
}
