package at.koopro.wizardsandbeasts.client.map;

import at.koopro.wizardsandbeasts.WizardsAndBeastsMod;
import net.minecraft.resources.Identifier;

/**
 * Every texture the map screen draws, and the sheet geometry needed to address a cell in one.
 *
 * <p>Sheets rather than a file per symbol. The terrain pass blits one sprite per visible tile and
 * there can be two thousand of those in a frame; a file per tile type would be a texture bind per
 * tile type per frame, which is the difference between a map that opens instantly and one that
 * hitches. All of it is generated by {@code tools/map_textures.py}.
 *
 * <p>The tile and marker sheets are authored <em>greyscale</em> and tinted at draw time, the same
 * convention the skill chart uses. One forest sprite serves the dark forest, the birch wood and a
 * modded biome a pack has styled green, and a resource pack recolours the whole map by editing
 * JSON rather than by repainting a sheet.
 */
public final class MaraudersMapTextures {

    private MaraudersMapTextures() {
    }

    private static Identifier map(String path) {
        return Identifier.fromNamespaceAndPath(WizardsAndBeastsMod.MODID, "textures/gui/map/" + path);
    }

    /** The material the panel is cut from — parchment, ink and tarnished brass. */
    public static final String SKIN = "marauders_map";

    // -- Terrain sheet -----------------------------------------------------

    /** Terrain cells. Greyscale, tinted per biome style. */
    public static final Identifier TILES = map("tiles.png");

    /**
     * Four hand-drawn variants of every terrain type, laid out one type per row.
     *
     * <p>A sheet with one cell per terrain type produces a forest that is the same six trees stamped
     * four hundred times in a perfect grid, which is the single thing that makes a procedural map
     * read as procedural. Picking a variant from a hash of the tile's own coordinates breaks the
     * grid without storing anything and without flickering when the map is panned, because the hash
     * is of world position rather than of screen position.
     *
     * <p>Row-per-type rather than a packed grid so that adding a terrain type appends a row and
     * changes no existing index — every {@code tile} value already written into a resource pack
     * keeps meaning what it meant.
     */
    public static final int TILE_VARIANTS = 4;
    /** Rows on the sheet. Sized past the shipped set so new types do not resize the file. */
    public static final int TILE_TYPES = 32;
    /** Native size of one tile cell, in texels. */
    public static final int TILE_CELL = 16;
    public static final int TILE_SHEET_W = TILE_VARIANTS * TILE_CELL;
    public static final int TILE_SHEET_H = TILE_TYPES * TILE_CELL;

    public static int tileU(int variant) {
        return Math.floorMod(variant, TILE_VARIANTS) * TILE_CELL;
    }

    public static int tileV(int type) {
        return Math.floorMod(type, TILE_TYPES) * TILE_CELL;
    }

    /**
     * Which of a type's {@link #TILE_VARIANTS} to draw at a world tile.
     *
     * <p>A cheap integer hash rather than a {@code Random}: it has to be stable across frames and
     * across sessions — the same wood must look like the same wood tomorrow — and it is evaluated
     * once per visible tile per frame, so it cannot allocate.
     */
    public static int variantFor(int tileX, int tileZ) {
        int h = tileX * 0x9E3779B9 ^ tileZ * 0x85EBCA6B;
        h ^= h >>> 15;
        h *= 0x2545F491;
        h ^= h >>> 13;
        return Math.floorMod(h, TILE_VARIANTS);
    }

    // -- Marker sheet ------------------------------------------------------

    /** Marker symbols. Greyscale, tinted per marker style. */
    public static final Identifier MARKERS = map("markers.png");
    public static final int MARKER_COLUMNS = 8;
    public static final int MARKER_ROWS = 4;
    public static final int MARKER_CELL = 16;
    public static final int MARKER_SHEET_W = MARKER_COLUMNS * MARKER_CELL;
    public static final int MARKER_SHEET_H = MARKER_ROWS * MARKER_CELL;

    public static int markerU(int cell) {
        return (Math.floorMod(cell, MARKER_COLUMNS * MARKER_ROWS) % MARKER_COLUMNS) * MARKER_CELL;
    }

    public static int markerV(int cell) {
        return (Math.floorMod(cell, MARKER_COLUMNS * MARKER_ROWS) / MARKER_COLUMNS) * MARKER_CELL;
    }

    // -- Single sprites ----------------------------------------------------

    /** The holder's own mark: an ink arrow that turns with them. */
    public static final Identifier PLAYER_MARK = map("player_mark.png");
    public static final int PLAYER_MARK_SIZE = 16;

    /** Another tracked person or creature: a smaller ink pip with a heading nub. */
    public static final Identifier TRACKED_MARK = map("tracked_mark.png");
    public static final int TRACKED_MARK_SIZE = 16;

    /** A footprint in the trail behind a moving dot. */
    public static final Identifier FOOTPRINT = map("footprint.png");
    public static final int FOOTPRINT_SIZE = 8;

    /** Compass rose, drawn once in a corner of the parchment. */
    public static final Identifier COMPASS = map("compass.png");
    public static final int COMPASS_SIZE = 32;

    /** Paper grain, tiled across the whole page under the terrain. */
    public static final Identifier PARCHMENT = map("parchment.png");
    public static final int PARCHMENT_TILE = 64;

    /** Fold creases and edge burn, stretched over the page above the terrain. */
    public static final Identifier CREASES = map("creases.png");
    public static final int CREASES_SIZE = 256;

    // -- Controls ----------------------------------------------------------

    /** Icon controls, one row. */
    public static final Identifier CONTROLS = map("controls.png");
    public static final int CONTROL_CELL = 12;
    public static final int CONTROL_COLUMNS = 8;
    public static final int CONTROL_SHEET_W = CONTROL_COLUMNS * CONTROL_CELL;
    public static final int CONTROL_SHEET_H = CONTROL_CELL;

    public static final int ICON_ZOOM_IN = 0;
    public static final int ICON_ZOOM_OUT = 1;
    public static final int ICON_CENTER = 2;
    public static final int ICON_WAYPOINT = 3;
    public static final int ICON_LEGEND = 4;
    public static final int ICON_DELETE = 5;
    public static final int ICON_HIDE = 6;
    public static final int ICON_SHOW = 7;

    public static int controlU(int icon) {
        return Math.floorMod(icon, CONTROL_COLUMNS) * CONTROL_CELL;
    }
}
