package at.koopro.wizardsandbeasts.client.trinket;

import at.koopro.wizardsandbeasts.WizardsAndBeastsMod;
import at.koopro.wizardsandbeasts.registry.TrinketItemRegistry;
import net.minecraft.resources.Identifier;
import net.minecraft.world.item.ItemStack;
import net.neoforged.neoforge.client.extensions.common.IClientItemExtensions;
import net.neoforged.neoforge.client.extensions.common.RegisterClientExtensionsEvent;
import org.jspecify.annotations.NullMarked;

/**
 * Two lenses instead of one, for the only view of the Omnioculars a player ever really has.
 *
 * <p>While an optic is raised, the scope mask <em>is</em> the item: the hands are not drawn, the
 * world is squeezed into an aperture, and everything else about the object is off screen. Wearing
 * vanilla's single-circle spyglass mask therefore made the Omnioculars a spyglass with a different
 * name for the entire duration of their use.
 *
 * <p>{@code IClientItemExtensions#getScopeOverlayTexture} is the whole fix, and it is why the item
 * still extends {@code SpyglassItem}. The alternative considered — dropping the
 * {@code SPYGLASS_SCOPE} item ability so that {@code isScoping()} goes false and the first-person
 * hands render again — costs more than it returns: it also discards vanilla's zoom
 * ({@code AbstractClientPlayer#getFieldOfViewModifier} returns {@code 0.1F} on an early return that
 * skips {@code ComputeFovModifierEvent} entirely), the scope-scale ramp in {@code Gui}, and the
 * third-person render of the item at the holder's head
 * ({@code AvatarRenderer}'s {@code heldOnHead}, gated on that same ability) — which for binoculars
 * held to both eyes is exactly right. All of that would have to be rebuilt to reveal two hands that
 * a binocular mask covers anyway.
 *
 * <p>Third person keeps both arms regardless: that is
 * {@code at.koopro.wizardsandbeasts.client.pose.ItemUsePosePass}, which raises the free arm to match
 * the one vanilla's {@code ArmPose.SPYGLASS} already poses.
 */
@NullMarked
public final class OmniocularsClientExtensions implements IClientItemExtensions {

    /**
     * Generated by {@code tools/omnioculars_scope.py}, so the geometry and this path cannot drift.
     *
     * <p>{@code textures/misc/} rather than {@code textures/gui/}, matching where vanilla keeps
     * {@code spyglass_scope.png} — this is a camera mask, not a widget.
     */
    public static final Identifier SCOPE_TEXTURE =
            Identifier.fromNamespaceAndPath(WizardsAndBeastsMod.MODID, "textures/misc/omnioculars_scope.png");

    private static final OmniocularsClientExtensions INSTANCE = new OmniocularsClientExtensions();

    private OmniocularsClientExtensions() {}

    public static void register(RegisterClientExtensionsEvent event) {
        event.registerItem(INSTANCE, TrinketItemRegistry.OMNI_OCULARS.get());
    }

    @Override
    public Identifier getScopeOverlayTexture(ItemStack stack) {
        return SCOPE_TEXTURE;
    }
}
