package at.koopro.wizardsandbeasts.registry;

import net.minecraft.world.item.Item;
import net.neoforged.neoforge.registries.DeferredItem;

import java.util.List;

/**
 * Canonical wizarding-world objects that the item audit found missing, registered as
 * behaviourless stubs.
 *
 * <p>Every entry here is a real item id with a real sprite, a real name and <em>no</em>
 * function: no use handler, no components beyond a stack size, no block, no entity. That is
 * the point. A stub a designer can hold in a creative tab and see next to the rest of the
 * wardrobe is a far better brief than a line in a document, and giving each one its id now
 * means the behaviour can land later without renaming anything or migrating a save.
 *
 * <p>Sources are recorded per item in the {@code .desc} lang key rather than here, so the
 * canon citation travels with the tooltip the player actually reads.
 *
 * <p>Several of these are placeholders for things that will not finally be items at all —
 * the Mirror of Erised, the Vanishing Cabinet and the Knight Bus want a block or an entity.
 * They are registered as items anyway so the whole catalogue is visible and orderable in one
 * place; converting one later is a registry move, not a rewrite.
 *
 * <p>Generated by {@code tools/canon_items.py} alongside the sprites, so the ids here and the
 * PNG filenames cannot drift apart.
 */
public final class CanonItemRegistry {

    // --- Deathly Hallows & legendary artefacts -----------------------------
    public static final DeferredItem<Item> TALES_OF_BEEDLE_THE_BARD =
            ModItems.ITEMS.registerItem("tales_of_beedle_the_bard", Item::new);
    public static final DeferredItem<Item> SWORD_OF_GRYFFINDOR =
            ModItems.ITEMS.registerItem("sword_of_gryffindor", Item::new);
    public static final DeferredItem<Item> MIRROR_OF_ERISED =
            ModItems.ITEMS.registerItem("mirror_of_erised", Item::new);
    public static final DeferredItem<Item> ELIXIR_OF_LIFE =
            ModItems.ITEMS.registerItem("elixir_of_life", Item::new);
    public static final DeferredItem<Item> GOBLET_OF_FIRE =
            ModItems.ITEMS.registerItem("goblet_of_fire", Item::new);
    public static final DeferredItem<Item> TRIWIZARD_CUP =
            ModItems.ITEMS.registerItem("triwizard_cup", Item::new);
    public static final DeferredItem<Item> GOLDEN_EGG =
            ModItems.ITEMS.registerItem("golden_egg", Item::new);

    // --- Founders' artefacts -----------------------------------------------
    public static final DeferredItem<Item> SORTING_HAT =
            ModItems.ITEMS.registerItem("sorting_hat", Item::new);

    // --- Dark artefacts & cursed objects -----------------------------------
    public static final DeferredItem<Item> BASILISK_FANG =
            ModItems.ITEMS.registerItem("basilisk_fang", Item::new);
    public static final DeferredItem<Item> VANISHING_CABINET =
            ModItems.ITEMS.registerItem("vanishing_cabinet", Item::new);
    public static final DeferredItem<Item> OPAL_NECKLACE =
            ModItems.ITEMS.registerItem("opal_necklace", Item::new);
    public static final DeferredItem<Item> SECRETS_OF_THE_DARKEST_ART =
            ModItems.ITEMS.registerItem("secrets_of_the_darkest_art", Item::new);
    public static final DeferredItem<Item> MOSTE_POTENTE_POTIONS =
            ModItems.ITEMS.registerItem("moste_potente_potions", Item::new);
    public static final DeferredItem<Item> ACROMANTULA_VENOM =
            ModItems.ITEMS.registerItem("acromantula_venom", Item::new);
    public static final DeferredItem<Item> SHRUNKEN_HEAD =
            ModItems.ITEMS.registerItem("shrunken_head", Item::new);

    // --- Detection & surveillance ------------------------------------------
    public static final DeferredItem<Item> SECRECY_SENSOR =
            ModItems.ITEMS.registerItem("secrecy_sensor", Item::new);
    public static final DeferredItem<Item> PROBITY_PROBE =
            ModItems.ITEMS.registerItem("probity_probe", Item::new);
    public static final DeferredItem<Item> REVEALER =
            ModItems.ITEMS.registerItem("revealer", Item::new);

    // --- Communication & information ---------------------------------------
    public static final DeferredItem<Item> HOWLER =
            ModItems.ITEMS.registerItem("howler", Item::new);
    public static final DeferredItem<Item> DA_GALLEON =
            ModItems.ITEMS.registerItem("da_galleon", Item::new);
    public static final DeferredItem<Item> DAILY_PROPHET =
            ModItems.ITEMS.registerItem("daily_prophet", Item::new);
    public static final DeferredItem<Item> THE_QUIBBLER =
            ModItems.ITEMS.registerItem("the_quibbler", Item::new);
    public static final DeferredItem<Item> WIZARDING_WIRELESS =
            ModItems.ITEMS.registerItem("wizarding_wireless", Item::new);
    public static final DeferredItem<Item> QUICK_QUOTES_QUILL =
            ModItems.ITEMS.registerItem("quick_quotes_quill", Item::new);
    public static final DeferredItem<Item> AUTO_ANSWER_QUILL =
            ModItems.ITEMS.registerItem("auto_answer_quill", Item::new);

    // --- Transportation ----------------------------------------------------
    public static final DeferredItem<Item> KNIGHT_BUS =
            ModItems.ITEMS.registerItem("knight_bus", Item::new);
    public static final DeferredItem<Item> FLYING_FORD_ANGLIA =
            ModItems.ITEMS.registerItem("flying_ford_anglia", Item::new);
    public static final DeferredItem<Item> THESTRAL_CARRIAGE =
            ModItems.ITEMS.registerItem("thestral_carriage", Item::new);
    public static final DeferredItem<Item> BROOMSTICK_SERVICING_KIT =
            ModItems.ITEMS.registerItem("broomstick_servicing_kit", Item::new);

    // --- Weasleys' Wizard Wheezes ------------------------------------------
    public static final DeferredItem<Item> SKIVING_SNACKBOX =
            ModItems.ITEMS.registerItem("skiving_snackbox", Item::new);
    public static final DeferredItem<Item> PUKING_PASTILLES =
            ModItems.ITEMS.registerItem("puking_pastilles", Item::new);
    public static final DeferredItem<Item> NOSEBLEED_NOUGAT =
            ModItems.ITEMS.registerItem("nosebleed_nougat", Item::new);
    public static final DeferredItem<Item> FAINTING_FANCIES =
            ModItems.ITEMS.registerItem("fainting_fancies", Item::new);
    public static final DeferredItem<Item> FEVER_FUDGE =
            ModItems.ITEMS.registerItem("fever_fudge", Item::new);
    public static final DeferredItem<Item> HEADLESS_HAT =
            ModItems.ITEMS.registerItem("headless_hat", Item::new);
    public static final DeferredItem<Item> SHIELD_HAT =
            ModItems.ITEMS.registerItem("shield_hat", Item::new);
    public static final DeferredItem<Item> SHIELD_CLOAK =
            ModItems.ITEMS.registerItem("shield_cloak", Item::new);
    public static final DeferredItem<Item> SHIELD_GLOVES =
            ModItems.ITEMS.registerItem("shield_gloves", Item::new);
    public static final DeferredItem<Item> PORTABLE_SWAMP =
            ModItems.ITEMS.registerItem("portable_swamp", Item::new);
    public static final DeferredItem<Item> WILDFIRE_WHIZ_BANGS =
            ModItems.ITEMS.registerItem("wildfire_whiz_bangs", Item::new);
    public static final DeferredItem<Item> TON_TONGUE_TOFFEE =
            ModItems.ITEMS.registerItem("ton_tongue_toffee", Item::new);
    public static final DeferredItem<Item> CANARY_CREAM =
            ModItems.ITEMS.registerItem("canary_cream", Item::new);
    public static final DeferredItem<Item> DUNGBOMB =
            ModItems.ITEMS.registerItem("dungbomb", Item::new);
    public static final DeferredItem<Item> FILIBUSTERS_FIREWORKS =
            ModItems.ITEMS.registerItem("filibusters_fireworks", Item::new);
    public static final DeferredItem<Item> PUNCHING_TELESCOPE =
            ModItems.ITEMS.registerItem("punching_telescope", Item::new);
    public static final DeferredItem<Item> U_NO_POO =
            ModItems.ITEMS.registerItem("u_no_poo", Item::new);

    // --- Educational & school ----------------------------------------------
    public static final DeferredItem<Item> STANDARD_BOOK_OF_SPELLS =
            ModItems.ITEMS.registerItem("standard_book_of_spells", Item::new);
    public static final DeferredItem<Item> DRAGON_HIDE_GLOVES =
            ModItems.ITEMS.registerItem("dragon_hide_gloves", Item::new);
    public static final DeferredItem<Item> MONSTER_BOOK_OF_MONSTERS =
            ModItems.ITEMS.registerItem("monster_book_of_monsters", Item::new);
    public static final DeferredItem<Item> ADVANCED_POTION_MAKING =
            ModItems.ITEMS.registerItem("advanced_potion_making", Item::new);
    public static final DeferredItem<Item> QUILL =
            ModItems.ITEMS.registerItem("quill", Item::new);
    public static final DeferredItem<Item> BRASS_SCALES =
            ModItems.ITEMS.registerItem("brass_scales", Item::new);
    public static final DeferredItem<Item> TELESCOPE =
            ModItems.ITEMS.registerItem("telescope", Item::new);
    public static final DeferredItem<Item> MAGICAL_DRAUGHTS_AND_POTIONS =
            ModItems.ITEMS.registerItem("magical_draughts_and_potions", Item::new);
    public static final DeferredItem<Item> FANTASTIC_BEASTS_AND_WHERE_TO_FIND_THEM =
            ModItems.ITEMS.registerItem("fantastic_beasts_and_where_to_find_them", Item::new);
    public static final DeferredItem<Item> QUIDDITCH_THROUGH_THE_AGES =
            ModItems.ITEMS.registerItem("quidditch_through_the_ages", Item::new);
    public static final DeferredItem<Item> ONE_THOUSAND_MAGICAL_HERBS_AND_FUNGI =
            ModItems.ITEMS.registerItem("one_thousand_magical_herbs_and_fungi", Item::new);
    public static final DeferredItem<Item> BEGINNERS_GUIDE_TO_TRANSFIGURATION =
            ModItems.ITEMS.registerItem("beginners_guide_to_transfiguration", Item::new);
    public static final DeferredItem<Item> UNFOGGING_THE_FUTURE =
            ModItems.ITEMS.registerItem("unfogging_the_future", Item::new);
    public static final DeferredItem<Item> WIZARDS_CHESS_SET =
            ModItems.ITEMS.registerItem("wizards_chess_set", Item::new);
    public static final DeferredItem<Item> GOBSTONES =
            ModItems.ITEMS.registerItem("gobstones", Item::new);
    public static final DeferredItem<Item> EXPLODING_SNAP =
            ModItems.ITEMS.registerItem("exploding_snap", Item::new);

    // --- Quidditch ---------------------------------------------------------
    public static final DeferredItem<Item> GOLDEN_SNITCH =
            ModItems.ITEMS.registerItem("golden_snitch", Item::new);
    public static final DeferredItem<Item> QUAFFLE =
            ModItems.ITEMS.registerItem("quaffle", Item::new);
    public static final DeferredItem<Item> BLUDGER =
            ModItems.ITEMS.registerItem("bludger", Item::new);
    public static final DeferredItem<Item> BEATERS_BAT =
            ModItems.ITEMS.registerItem("beaters_bat", Item::new);
    public static final DeferredItem<Item> QUIDDITCH_ROBES =
            ModItems.ITEMS.registerItem("quidditch_robes", Item::new);

    // --- Potions & remedies ------------------------------------------------
    //
    // Eight canon potions used to be registered here as behaviourless Item::new stubs. They are now
    // BREWS -- data in data/<ns>/brews/ with brewing_recipes/ to make them, produced as BrewItem
    // stacks carrying a BREW_ID component.
    //
    // Removing them rather than leaving both is the point. A `polyjuice_potion` item that did nothing
    // sitting in the creative tab next to a Polyjuice Potion you can actually brew is two things with
    // one name, and the dead one is the one a player finds first. Nothing referenced these outside
    // this file, so the only cost is that a creative-mode stack of the old item disappears -- which is
    // the honest outcome for an item that never did anything.
    //
    // The remedies below stay items on purpose: they are ingredients and consumables with their own
    // behaviour, not brews with recipes.
    public static final DeferredItem<Item> ESSENCE_OF_DITTANY =
            ModItems.ITEMS.registerItem("essence_of_dittany", Item::new);
    public static final DeferredItem<Item> MURTLAP_ESSENCE =
            ModItems.ITEMS.registerItem("murtlap_essence", Item::new);
    public static final DeferredItem<Item> DRAUGHT_OF_PEACE =
            ModItems.ITEMS.registerItem("draught_of_peace", Item::new);
    public static final DeferredItem<Item> BLOOD_REPLENISHING_POTION =
            ModItems.ITEMS.registerItem("blood_replenishing_potion", Item::new);

    // --- Other notable objects ---------------------------------------------
    public static final DeferredItem<Item> CHOCOLATE_BAR =
            ModItems.ITEMS.registerItem("chocolate_bar", Item::new);
    public static final DeferredItem<Item> MEMORY_VIAL =
            ModItems.ITEMS.registerItem("memory_vial", Item::new);
    public static final DeferredItem<Item> GUBRAITHIAN_FIRE =
            ModItems.ITEMS.registerItem("gubraithian_fire", Item::new);
    public static final DeferredItem<Item> SPELLOTAPE =
            ModItems.ITEMS.registerItem("spellotape", Item::new);
    public static final DeferredItem<Item> MRS_SKOWERS_MESS_REMOVER =
            ModItems.ITEMS.registerItem("mrs_skowers_mess_remover", Item::new);
    public static final DeferredItem<Item> FLESH_EATING_SLUG_REPELLENT =
            ModItems.ITEMS.registerItem("flesh_eating_slug_repellent", Item::new);
    public static final DeferredItem<Item> SELF_STIRRING_CAULDRON =
            ModItems.ITEMS.registerItem("self_stirring_cauldron", Item::new);
    public static final DeferredItem<Item> COLLAPSIBLE_CAULDRON =
            ModItems.ITEMS.registerItem("collapsible_cauldron", Item::new);

    /**
     * Every stub, in catalogue order.
     *
     * <p>Held here so the creative tab does not keep a hand-copied roster that goes stale the
     * moment an entry is added or promoted out of this class.
     */
    public static final List<DeferredItem<Item>> ALL = List.of(
            TALES_OF_BEEDLE_THE_BARD, SWORD_OF_GRYFFINDOR, MIRROR_OF_ERISED,
            ELIXIR_OF_LIFE, GOBLET_OF_FIRE, TRIWIZARD_CUP,
            GOLDEN_EGG, SORTING_HAT, BASILISK_FANG,
            VANISHING_CABINET, OPAL_NECKLACE, SECRETS_OF_THE_DARKEST_ART,
            MOSTE_POTENTE_POTIONS, ACROMANTULA_VENOM, SHRUNKEN_HEAD,
            SECRECY_SENSOR, PROBITY_PROBE, REVEALER,
            HOWLER, DA_GALLEON, DAILY_PROPHET,
            THE_QUIBBLER, WIZARDING_WIRELESS, QUICK_QUOTES_QUILL,
            AUTO_ANSWER_QUILL, KNIGHT_BUS, FLYING_FORD_ANGLIA,
            THESTRAL_CARRIAGE, BROOMSTICK_SERVICING_KIT, SKIVING_SNACKBOX,
            PUKING_PASTILLES, NOSEBLEED_NOUGAT, FAINTING_FANCIES,
            FEVER_FUDGE, HEADLESS_HAT, SHIELD_HAT,
            SHIELD_CLOAK, SHIELD_GLOVES, PORTABLE_SWAMP,
            WILDFIRE_WHIZ_BANGS, TON_TONGUE_TOFFEE, CANARY_CREAM,
            DUNGBOMB, FILIBUSTERS_FIREWORKS, PUNCHING_TELESCOPE,
            U_NO_POO, STANDARD_BOOK_OF_SPELLS, DRAGON_HIDE_GLOVES,
            MONSTER_BOOK_OF_MONSTERS, ADVANCED_POTION_MAKING, QUILL,
            BRASS_SCALES, TELESCOPE, MAGICAL_DRAUGHTS_AND_POTIONS,
            FANTASTIC_BEASTS_AND_WHERE_TO_FIND_THEM, QUIDDITCH_THROUGH_THE_AGES, ONE_THOUSAND_MAGICAL_HERBS_AND_FUNGI,
            BEGINNERS_GUIDE_TO_TRANSFIGURATION, UNFOGGING_THE_FUTURE, WIZARDS_CHESS_SET,
            GOBSTONES, EXPLODING_SNAP, GOLDEN_SNITCH,
            QUAFFLE, BLUDGER, BEATERS_BAT,
            QUIDDITCH_ROBES,
            ESSENCE_OF_DITTANY, MURTLAP_ESSENCE, DRAUGHT_OF_PEACE,
            BLOOD_REPLENISHING_POTION, CHOCOLATE_BAR, MEMORY_VIAL,
            GUBRAITHIAN_FIRE, SPELLOTAPE, MRS_SKOWERS_MESS_REMOVER,
            FLESH_EATING_SLUG_REPELLENT, SELF_STIRRING_CAULDRON, COLLAPSIBLE_CAULDRON);

    private CanonItemRegistry() {}

    public static void init() {}
}
