#!/usr/bin/env python3
"""Real 3D models for the items that are held, not just listed.

`item_icons.py` and `canon_sprites.py` gave every item a proper sprite, but a sprite is
still a flat card: Minecraft extrudes `item/generated` into a wafer, so a goblet in your
hand is a goblet-shaped biscuit. For the props a player actually holds — potions, books,
wands' cores, a Snitch, the Sword of Gryffindor — a few cuboids read enormously better in
first person, on the ground and in an item frame.

Each item is authored once as a list of boxes. Both outputs come from that one list:

  - `models/item/<id>.json`  the cuboid model, with per-face UVs pointing into
  - `textures/item/<id>_3d.png`  a box-UV atlas painted to match

Deriving both from the same source is the point. A hand-authored model and a
hand-authored texture drift the moment either is edited; here a box cannot be moved
without its UVs moving with it.

The flat sprite stays on disk and is still what the inventory shows for items this tool
does not cover, so nothing regresses if an item is dropped from the list. Base colours are
lifted from the sprite catalogues in `item_icons.py` and `canon_sprites.py` so the model
and the icon are recognisably the same object.

Two things a box carries besides its extents:

  - a *material*, which decides how its faces are painted. Sixteen surface treatments,
    because "brass" and "bone" and "velvet" are not the same object in a different hue,
    and a cuboid with nothing but a flat fill and a light direction reads as a brick.
  - an optional *rotation*, so a Snitch's wing or a quill's shaft can lean. Minecraft
    allows one axis per element at ±22.5 or ±45 degrees, and nothing else.

Run from the repo root:  python tools/item_models_3d.py [--force] [--only id,id]
                         python tools/item_models_3d.py --list
"""

import argparse
import json
import math
import os
import re
import sys

from PIL import Image

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from artgen_common import hx, is_regenerable, marker, mix, posterise, save  # noqa: E402
import item_display  # noqa: E402

ASSETS = "src/main/resources/assets/wizards_and_beasts"
ITEM_TEX_DIR = os.path.join(ASSETS, "textures", "item")
ITEM_MODEL_DIR = os.path.join(ASSETS, "models", "item")
GENERATED_MODEL_DIR = "src/generated/resources/assets/wizards_and_beasts/models/item"
MODEL_PROVIDER = "src/main/java/at/koopro/wizardsandbeasts/datagen/ModModelProvider.java"
CANON_REGISTRY = "src/main/java/at/koopro/wizardsandbeasts/registry/CanonItemRegistry.java"

MARKER = marker("item_models_3d.py")
CREDIT = "generated by tools/item_models_3d.py"

# Texels per model unit. At 1 a bottle's belly got six texels across and every material
# treatment below — a brushed band, a page edge, a facet — landed on the same two or three
# pixels and turned to mush. 2 is the first density where they read as what they are, and
# still leaves a 12-unit-wide book cover at 24 texels, comfortably inside a 128px sheet.
DETAIL = 2

# Grown to fit rather than fixed: a four-box vial packs into 32px and a seven-box Pensieve
# needs 128. Face UVs in a model are always on a 0..16 scale regardless of resolution,
# hence a UV scale derived from whichever size the item ended up needing.
ATLAS_SIZES = (32, 64, 128, 256)

# How each prop is held is not written here: `item_display.py` derives every display transform
# from the model's own bounds and the hold class its builder is tagged with (see HOLD_BY_BUILDER).

# Directional light baked into the texture, matching the beast skins: top lit, underside
# dark, front brighter than back. Item models get no dynamic shading in the GUI, so
# without this a cuboid reads as a flat silhouette.
FACE_SHADE = {"up": 1.22, "down": 0.68, "north": 1.04, "south": 0.90, "east": 0.84, "west": 0.98}
HILIGHT = (255, 246, 224)
SHADOW = (16, 14, 24)

# Base grey for a tinted box. Minecraft tinting is *multiplicative*, so whatever is painted
# here is multiplied by the runtime colour: paint it in colour and you get that colour times
# the brew's, which is nobody's idea of Felix Felicis. Near-white keeps the result faithful to
# the tint while leaving enough headroom below 255 for the shading and specular band to survive.
TINT_BASE = "#e2e2e2"


def lit(rgb, f):
    if f >= 1.0:
        return mix(rgb + (255,), HILIGHT + (255,), min(0.55, (f - 1.0) * 0.95))[:3]
    return mix(rgb + (255,), SHADOW + (255,), min(0.60, (1.0 - f) * 0.95))[:3]


def noise(seed, x, y):
    n = (x * 374761393 + y * 668265263 + seed * 1274126177) & 0xFFFFFFFF
    n = ((n ^ (n >> 13)) * 1274126177) & 0xFFFFFFFF
    return ((n ^ (n >> 16)) & 0xFFFF) / 65535.0


# --------------------------------------------------------------------------- materials
#
# A material is a function of the position within one face. It returns a light multiplier
# and, optionally, a colour to blend over the result — a crack, a glint, a line of type.
# Everything about how a surface looks lives here rather than in the catalogue, so a box
# only has to say what it is made of.
#
#   (i, j)   texel within the face, origin top-left
#   (fw, fh) face size in texels
#   face     which of the six, for treatments that only make sense on a side or a top
#   seed     stable per-box, so a grain pattern does not shift between runs
#   rnd      noise(seed, i, j), precomputed because most materials want it

def m_solid(i, j, fw, fh, face, seed, rnd):
    return 1.0, None


def m_glass(i, j, fw, fh, face, seed, rnd):
    """A bright vertical band down one side, which is what sells a cuboid as a bottle."""
    if face in ("up", "down"):
        return 1.08, None
    f = 1.0
    if fw >= 4 and i == max(1, fw // 6):
        f = 1.42
    elif fw >= 6 and i == fw - 2:
        f = 0.80
    return f, None


def m_liquid(i, j, fw, fh, face, seed, rnd):
    """Darkens with depth and catches the light at the meniscus."""
    if face == "up":
        return 1.20, None
    if face == "down":
        return 0.72, None
    f = 1.10 - 0.36 * (j / max(1, fh - 1))
    if j == 0:
        f = 1.40
    if fw >= 4 and i == max(1, fw // 6):
        f *= 1.12
    return f, None


def m_paper(i, j, fw, fh, face, seed, rnd):
    """Ruled leaves on the flat, cut page edges on the sides of a page block."""
    if face in ("east", "west") and fw >= 3:
        return (1.06 if i % 2 == 0 else 0.90), None
    return (1.03 if j % 2 == 0 else 0.96), None


def m_print(i, j, fw, fh, face, seed, rnd):
    """A masthead over ragged-right lines of type, in two columns with a gutter.

    Every other row set full width is not text, it is a venetian blind. Lines every third
    row, each ending where its own noise says, is the least that reads as print.
    """
    if face in ("north", "south") and fw >= 10 and fh >= 10:
        if 2 <= j <= 3 and 2 < i < fw - 2:
            return 1.0, ((40, 36, 34), 0.74)
        gutter = fw // 2
        if j >= 6 and (j - 6) % 3 == 0 and 2 < i < fw - 2 and abs(i - gutter) > 1:
            column = 0 if i < gutter else 1
            start = 3 if column == 0 else gutter + 2
            end = gutter - 2 if column == 0 else fw - 3
            run = start + 2 + noise(seed + 3, column, j) * (end - start - 2)
            if start <= i <= run:
                return 1.0, ((78, 74, 68), 0.46)
    return 1.02, None


def m_leather(i, j, fw, fh, face, seed, rnd):
    """Grain, plus a blind-tooled rule inset from the edge on any face big enough."""
    f = 0.94 + 0.13 * rnd
    if fw >= 8 and fh >= 8 and 2 <= i <= fw - 3 and 2 <= j <= fh - 3 \
            and (i in (2, fw - 3) or j in (2, fh - 3)):
        f *= 0.84
    return f, None


def m_metal(i, j, fw, fh, face, seed, rnd):
    """Lit from above with one brushed sheen band a third of the way down."""
    f = 0.86 + 0.34 * (1.0 - j / max(1, fh - 1))
    if fh >= 6 and j == fh // 3:
        f *= 1.22
    return f * (0.98 + 0.04 * rnd), None


def m_gold(i, j, fw, fh, face, seed, rnd):
    f, _ = m_metal(i, j, fw, fh, face, seed, rnd)
    return f * 1.05, (((255, 250, 214), 0.60) if rnd > 0.965 else None)


def m_gem(i, j, fw, fh, face, seed, rnd):
    """Four facets meeting at the centre, and a glint on the lit corner.

    Only on a face with room for them: split four ways, a face six texels across gives each
    facet three texels, and four competing three-texel wedges read as dither rather than as a
    cut. Small faces take one flat tone and let the silhouette do the work.
    """
    if fw < 8 or fh < 8:
        return 1.06, (((255, 255, 255), 0.35) if i <= 1 and j <= 1 else None)
    u = i / (fw - 1) - 0.5
    v = j / (fh - 1) - 0.5
    f = (0.84, 0.94, 1.06, 1.20)[(1 if u + v > 0 else 0) + (2 if u - v < 0 else 0)]
    if i <= 1 and j <= 1:
        f = 1.34
    return f, None


def m_wood(i, j, fw, fh, face, seed, rnd):
    """Grain runs along the face's long axis, which is the way the plank was cut."""
    g = noise(seed + 11, (i if fh >= fw else j), 0)
    f = 0.90 + 0.18 * g
    if g > 0.88:
        f *= 0.78
    return f * (0.97 + 0.06 * rnd), None


def m_cloth(i, j, fw, fh, face, seed, rnd):
    """A soft weave and the occasional fold.

    Alternating every texel at full strength turned a cloak into wire mesh, so the weave is
    barely there and the folds — sparser, and running only down the face — carry the surface.
    """
    f = 1.02 if (i + j) % 2 == 0 else 0.98
    if fw >= 8 and i % max(4, fw // 3) == 0:
        f *= 0.91
    return f * (0.98 + 0.04 * rnd), None


def m_fur(i, j, fw, fh, face, seed, rnd):
    return 0.80 + 0.42 * noise(seed + 5, i, j // 2), None


def m_bone(i, j, fw, fh, face, seed, rnd):
    """Pale and lit from the tip, cracked here and there, yellowing at the root."""
    f = 1.0 + 0.14 * (1.0 - j / max(1, fh - 1))
    if rnd > 0.945:
        return f, ((150, 140, 112), 0.45)
    if j > fh * 0.68 and rnd > 0.72:
        return f, ((196, 176, 122), 0.32)
    return f, None


def m_stone(i, j, fw, fh, face, seed, rnd):
    f = 0.88 + 0.26 * noise(seed + 2, i // 2, j // 2)
    return (f * 0.82 if rnd > 0.92 else f), None


def m_candy(i, j, fw, fh, face, seed, rnd):
    """One round specular blob up and to the left: the whole of what makes a thing glossy."""
    r = max(1.0, min(fw, fh) * 0.24)
    d = math.hypot(i - fw * 0.30, j - fh * 0.28)
    if d <= r:
        return 1.0, ((255, 255, 255), 0.58 * (1.0 - d / (r + 1.0)))
    return 1.0 + 0.12 * (1.0 - j / max(1, fh - 1)), None


def m_dark(i, j, fw, fh, face, seed, rnd):
    """Velvet: almost no shading, and the occasional cold spark in it."""
    f = 0.92 + 0.10 * rnd
    return f, (((150, 130, 200), 0.32) if rnd > 0.975 else None)


def m_glow(i, j, fw, fh, face, seed, rnd):
    """Not actually emissive — item models get no light — but lit flat and bright enough
    that it reads as the thing giving off light rather than the thing catching it."""
    return 1.22 + 0.22 * noise(seed + 9, i, j), None


def m_feather(i, j, fw, fh, face, seed, rnd):
    """A dark rachis down the middle with barbs combing off it."""
    if fw <= 2 or fh <= 2:
        return 1.0, None
    if i == fw // 2:
        return 0.70, None
    return (1.14 if (i + j) % 3 == 0 else 0.95), None


MATERIALS = {
    "solid": m_solid, "glass": m_glass, "liquid": m_liquid, "paper": m_paper,
    "print": m_print, "leather": m_leather, "metal": m_metal, "gold": m_gold,
    "gem": m_gem, "wood": m_wood, "cloth": m_cloth, "fur": m_fur, "bone": m_bone,
    "stone": m_stone, "candy": m_candy, "dark": m_dark, "glow": m_glow,
    "feather": m_feather,
}


# --------------------------------------------------------------------------- geometry

ROTATION_ANGLES = (-45.0, -22.5, 0.0, 22.5, 45.0)


class Box:
    """One cuboid: model-space extents in 0..16, a colour, a material, and a rotation.

    `tint=True` hands the box's colour over to the game: it is painted greyscale and its faces
    carry `tintindex: 0`, so an ItemTintSource decides what colour it actually is at render
    time. That is what lets one bottle model serve every brew in the catalogue, including ones
    a datapack adds after the model was generated.
    """

    def __init__(self, frm, to, colour, material="solid", tint=False, rot=None, ao=1.0, cover=None):
        if material not in MATERIALS:
            raise SystemExit(f"unknown material {material!r}")
        self.frm = [float(v) for v in frm]
        self.to = [float(v) for v in to]
        self.colour = hx(TINT_BASE if tint else colour)[:3]
        self.material = material
        self.tint = tint
        # How hard this box darkens its own edges. Full strength outlines the box, which is
        # right for a book board and wrong for one of three arms making up a sphere: there,
        # every interior seam gets drawn and the ball reads as a knobbly plus. Assemblies that
        # are meant to look like one solid turn it down.
        self.ao = float(ao)
        # The face that shows the item's own cover art (a book's front board), or None. The art
        # itself is attached at build time, from the item's 16x16 icon -- see cover_art().
        self.cover = cover
        self.decal = None
        self.rot = None
        if rot:
            self.set_rotation(*rot)

    def set_rotation(self, axis, angle, origin):
        # Minecraft rejects anything else outright, and a model that fails to load is a
        # purple-and-black cube with no error the player can see.
        if axis not in ("x", "y", "z"):
            raise SystemExit(f"rotation axis must be x, y or z, got {axis!r}")
        if float(angle) not in ROTATION_ANGLES:
            raise SystemExit(f"rotation angle must be one of {ROTATION_ANGLES}, got {angle!r}")
        self.rot = (axis, float(angle), [float(v) for v in origin])

    def size_texels(self):
        """Footprint in texels, clamped to at least 1 so a paper-thin box still has a face."""
        return [max(1, int(math.ceil((self.to[a] - self.frm[a]) * DETAIL))) for a in range(3)]


def tilt(boxes, axis, angle, origin=(8, 8, 8)):
    """Lean a whole assembly. Every box turns about the same origin, so it stays assembled."""
    for box in boxes:
        box.set_rotation(axis, angle, origin)
    return boxes


def net_size(box):
    w, h, d = box.size_texels()
    return 2 * d + 2 * w, d + h


def pack(boxes, width, gap=1):
    """Shelf-pack each box's UV net. Same approach as beast_skins, at item scale."""
    placements = {}
    x = y = gap
    shelf = 0
    for index, box in sorted(enumerate(boxes), key=lambda pair: -net_size(pair[1])[1]):
        nw, nh = net_size(box)
        if nw + 2 * gap > width:
            return None, width + 1          # this box cannot fit this sheet at any offset
        if x + nw + gap > width:
            x = gap
            y += shelf + gap
            shelf = 0
        placements[index] = (x, y)
        x += nw + gap
        shelf = max(shelf, nh)
    return placements, y + shelf + gap


def fit_atlas(boxes):
    """Smallest square sheet the whole item packs into."""
    for size in ATLAS_SIZES:
        placements, height = pack(boxes, size)
        if placements is not None and height <= size:
            return size, placements
    raise SystemExit("item does not pack into a 256px sheet; give it fewer or smaller boxes")


def face_rects(u, v, w, h, d):
    """Standard box-UV unwrap, in texels."""
    return {
        "up": (u + d, v, w, d),
        "down": (u + d + w, v, w, d),
        "east": (u, v + d, d, h),
        "north": (u + d, v + d, w, h),
        "west": (u + d + w, v + d, d, h),
        "south": (u + d + w + d, v + d, w, h),
    }


def texel_height(box, face, j):
    """Model-space Y of a texel, so the light can be about the object and not about the box.

    A face's net runs top-down, so row 0 is the top of a side face; the caps are flat.
    """
    if face == "up":
        return box.to[1]
    if face == "down":
        return box.frm[1]
    return box.to[1] - (j + 0.5) / DETAIL


def paint(img, box, rect, face, seed, span):
    """Paint one face's net: material, then the light. Cover art goes on after posterising."""
    x0, y0, fw, fh = rect
    px = img.load()
    _paint_material(px, box, rect, face, seed, span)


def _paint_decal(px, box, rect, face):
    """The icon's cover, at a whole-number scale and centred, lit like the face it sits on.

    Whole numbers only: a 1.8x nearest-neighbour stretch doubles every other icon pixel and the
    art turns lumpy. Whatever the integer fit leaves over keeps the board's own leather, which
    reads as the cover's margin.
    """
    x0, y0, fw, fh = rect
    art = box.decal
    k = max(1, min(fw // art.width, fh // art.height))
    art = art.resize((art.width * k, art.height * k), Image.NEAREST)
    ox, oy = x0 + (fw - art.width) // 2, y0 + (fh - art.height) // 2
    apx = art.load()
    shade = FACE_SHADE[face]
    for j in range(art.height):
        for i in range(art.width):
            r, g, b, a = apx[i, j]
            if a < 128 or not (x0 <= ox + i < x0 + fw and y0 <= oy + j < y0 + fh):
                continue
            px[ox + i, oy + j] = lit((r, g, b), shade)


def _paint_material(px, box, rect, face, seed, span):
    x0, y0, fw, fh = rect
    surface = MATERIALS[box.material]
    low, high = span
    for j in range(fh):
        for i in range(fw):
            f, overlay = surface(i, j, fw, fh, face, seed, noise(seed, i, j))
            f *= FACE_SHADE[face]
            # One light for the whole item, keyed to where the texel actually sits in model
            # space. Per-face shading alone lights every box as its own object, so a stack of
            # four boxes came out as four separately-lit slabs — which is most of why a hat
            # read as a ziggurat and a sphere read as a cluster.
            f *= 0.88 + 0.24 * (texel_height(box, face, j) - low) / max(0.001, high - low)
            # Contact shading. One ring at full strength alone left every face looking like
            # a sticker; a second, softer ring gives the cuboid a rounded edge instead.
            edge = min(i, j, fw - 1 - i, fh - 1 - j)
            if edge == 0:
                f *= 1.0 - 0.14 * box.ao
            elif edge == 1 and fw > 5 and fh > 5:
                f *= 1.0 - 0.06 * box.ao
            col = lit(box.colour, f)
            if overlay:
                col = mix(col + (255,), overlay[0] + (255,), overlay[1])[:3]
            px[x0 + i, y0 + j] = (col[0], col[1], col[2], 255)


def cover_art(item_id):
    """The cover region of the item's own icon: its opaque box, minus the page edge.

    Book icons are drawn cover-on with the fore-edge of the pages as a pale strip down the right;
    those columns are the page block, which the 3D book models as geometry, so they are cut off
    here. Columns are dropped from the right while they are mostly light.
    """
    path = os.path.join(ITEM_TEX_DIR, item_id + ".png")
    if not os.path.exists(path):
        return None
    icon = Image.open(path).convert("RGBA")
    bbox = icon.getbbox()
    if not bbox:
        return None
    icon = icon.crop(bbox)
    px = icon.load()

    def light(col):
        cells = [px[col, y] for y in range(icon.height) if px[col, y][3] >= 128]
        pale = [c for c in cells if 0.299 * c[0] + 0.587 * c[1] + 0.114 * c[2] > 150]
        return bool(cells) and len(pale) * 2 >= len(cells)

    right = icon.width
    while right > icon.width // 2 and (light(right - 1) or light(right - 2)):
        right -= 1
    return icon.crop((0, 0, right, icon.height))


def build(item_id, boxes, hold):
    art = None
    for box in boxes:
        if box.cover:
            art = art or cover_art(item_id)
            box.decal = art
    atlas, placements = fit_atlas(boxes)
    uv_scale = 16.0 / atlas
    img = Image.new("RGBA", (atlas, atlas), (0, 0, 0, 0))

    span = (min(b.frm[1] for b in boxes), max(b.to[1] for b in boxes))
    elements = []
    covers = []
    for index, box in enumerate(boxes):
        w, h, d = box.size_texels()
        u, v = placements[index]
        faces = {}
        for face, rect in face_rects(u, v, w, h, d).items():
            paint(img, box, rect, face, index * 31 + len(item_id), span)
            if box.decal is not None and face == box.cover:
                covers.append((box, rect, face))
            x0, y0, fw, fh = rect
            faces[face] = {"uv": [round(x0 * uv_scale, 4), round(y0 * uv_scale, 4),
                                  round((x0 + fw) * uv_scale, 4),
                                  round((y0 + fh) * uv_scale, 4)],
                           "texture": "#0"}
            if box.tint:
                faces[face]["tintindex"] = 0
        element = {"from": [round(v, 2) for v in box.frm],
                   "to": [round(v, 2) for v in box.to],
                   "faces": faces}
        if box.rot:
            axis, angle, origin = box.rot
            element["rotation"] = {"origin": [round(o, 2) for o in origin],
                                   "axis": axis, "angle": angle}
        elements.append(element)

    model = {
        "credit": CREDIT,
        "gui_light": "side",
        "textures": {"0": f"wizards_and_beasts:item/{item_id}_3d",
                     "particle": f"wizards_and_beasts:item/{item_id}_3d"},
        "elements": elements,
        "display": item_display.display_for(hold, item_display.cuboid_bounds(elements)),
    }
    # Enough palette entries for every material on every box to keep its own tones, but
    # still few enough that the sheet reads as Minecraft art rather than as a render.
    img = posterise(img, min(30, 8 + 3 * len({b.colour for b in boxes}) + len(boxes)))
    # Cover art last: it is already pixel art with its own small palette, and median-cut weights
    # colours by how many pixels carry them -- a gilt emblem of a dozen pixels on a board of
    # leather got folded into the leather and came out grey.
    px = img.load()
    for box, rect, face in covers:
        _paint_decal(px, box, rect, face)
    return img, model


def model_is_ours(path):
    """Safe to overwrite: absent, previously ours, or a bare item/generated stub.

    A stub is a model with nothing in it but a parent and a layer0 — replacing one with a
    real cuboid model is the entire point of this tool. Anything else was authored by
    hand and is left alone.
    """
    if not os.path.exists(path):
        return True
    try:
        with open(path, encoding="utf-8") as fh:
            doc = json.load(fh)
    except (OSError, ValueError):
        return False
    if doc.get("credit") == CREDIT:
        return True
    # Comment keys are not content: several stubs carry a "PLACEHOLDER texture" note, and
    # refusing to touch those would leave exactly the models this tool exists to replace.
    keys = {k for k in doc if not k.startswith("_") and k != "credit"}
    return (doc.get("parent") == "minecraft:item/generated"
            and keys <= {"parent", "textures"}
            and set(doc.get("textures", {})) <= {"layer0"})


# --------------------------------------------------------------------------- shapes
#
# Each builder returns a list of boxes in model space, 0..16 on every axis. They are
# deliberately blunt: four or five cuboids is all a prop this size can carry before the
# silhouette stops reading, and every extra box costs atlas.

def bottle(glass, liquid, tint=False, cork="#6b4a2f"):
    return [
        Box([5, 0.5, 5], [11, 7, 11], liquid, "liquid", tint),
        Box([5, 7, 5], [11, 10, 11], glass, "glass"),
        Box([6.5, 10, 6.5], [9.5, 13, 9.5], glass, "glass"),
        Box([6, 13, 6], [10, 14.5, 10], cork, "leather"),
    ]


def vial(glass, liquid, tint=False, liquid_style="liquid"):
    """`tint` hands the liquid box's colour to the game; glass, neck and cork stay fixed.

    Only the liquid, deliberately. Tinting the whole vial would drag the cork and the specular
    highlight along with it, and a Draught of Living Death would come with a black cork.
    """
    return [
        Box([6, 1, 6], [10, 7, 10], liquid, liquid_style, tint),
        Box([6, 7, 6], [10, 9, 10], glass, "glass"),
        Box([7, 9, 7], [9, 11.5, 9], glass, "glass"),
        Box([6.5, 11.5, 6.5], [9.5, 13, 9.5], "#6b4a2f", "leather"),
    ]


def flask(glass, liquid):
    """A wide belly under a long thin neck: the shape an essence comes in."""
    return [
        Box([4.5, 1, 4.5], [11.5, 6.5, 11.5], liquid, "liquid"),
        Box([5.5, 6.5, 5.5], [10.5, 8, 10.5], glass, "glass"),
        Box([7, 8, 7], [9, 13, 9], glass, "glass"),
        Box([6.5, 13, 6.5], [9.5, 14.5, 9.5], "#8f6b3f", "leather"),
    ]


def book(cover, pages="#e0d8c2", clasp=None, w=10, h=13, thick=1.5):
    """A closed book: two boards overhanging an inset page block, a spine that stands proud of
    them with two raised bands, and the title's own cover art on the front board.

    The first cut was boards flush with the pages and one leather colour on every face, which in
    the hand read as a coloured brick with a cream lid. What makes a book read at this size is the
    shadow line where the boards overhang the pages, the pale fore-edge between them, the ridged
    spine, and the cover -- which already exists, drawn, in the item's icon (see cover_art).

    Width and height still carry the identity as much as colour does: eleven books that differ
    only in hue are not eleven books.
    """
    x0, x1 = (16 - w) / 2, (16 + w) / 2
    y0, y1 = (16 - h) / 2, (16 + h) / 2
    depth = max(4.5, min(7.0, w * 0.55))
    z0, z1 = 8 - depth / 2, 8 + depth / 2
    boards = [
        Box([x0 + 0.5, y0, z0], [x1, y1, z0 + thick], cover, "leather"),
        Box([x0 + 0.5, y0, z1 - thick], [x1, y1, z1], cover, "leather", cover="south"),
    ]
    spine = Box([x0 - 0.25, y0 + 0.25, z0 + 0.25], [x0 + 1.25, y1 - 0.25, z1 - 0.25], cover, "leather")
    bands = [Box([x0 - 0.5, y, z0 + 0.5], [x0 + 0.5, y + 0.75, z1 - 0.5], cover, "leather", ao=0.6)
             for y in (y0 + h * 0.28, y1 - h * 0.28 - 0.75)]
    # Inset on the fore edge, head and tail, so the boards overhang it on three sides.
    block = Box([x0 + 1.25, y0 + 0.5, z0 + thick], [x1 - 0.5, y1 - 0.5, z1 - thick], pages, "paper")
    boxes = boards + [spine] + bands + [block]
    if clasp:
        boxes.append(Box([x1 - 1.5, 7, z0 - 0.3], [x1 + 0.5, 9, z1 + 0.3], clasp, "gold"))
    return boxes


def scroll(paper="#dcd2b4", ribbon="#8f2f3a"):
    return [
        Box([3, 6, 6], [13, 10, 10], paper, "paper"),
        Box([2.4, 5.6, 5.6], [3.4, 10.4, 10.4], paper, "paper"),
        Box([12.6, 5.6, 5.6], [13.6, 10.4, 10.4], paper, "paper"),
        Box([7, 5.6, 5.6], [9, 10.4, 10.4], ribbon, "cloth"),
    ]


def newspaper(paper="#c9c2ac"):
    """Folded once down the left, so the fold is the edge you see."""
    return [
        Box([2.5, 1.5, 6.4], [13.5, 14.5, 8], paper, "print"),
        Box([2.5, 1.5, 8], [13.5, 14.5, 9.6], paper, "paper"),
        Box([1.9, 1.5, 6.1], [2.9, 14.5, 9.9], paper, "paper"),
    ]


def envelope(paper, wax="#8c1a1a"):
    return [
        Box([2, 4, 7], [14, 12, 8.4], paper, "paper"),
        Box([2, 4, 8.4], [14, 12, 9.6], paper, "paper"),
        Box([6.5, 6.5, 6.1], [9.5, 9.5, 7.1], wax, "candy"),
    ]




def ball(colour, r=5, material="solid"):
    """A cube with six caps: the low-poly sphere.

    Three crossing bars alone leave a deep notch at all eight corners, so the thing reads as a
    knobbly plus however thin the arms get. A centre cube slightly wider than the arms fills
    those notches, and the arms become caps poking out of it — the same silhouette a chamfered
    sphere has. `ao` stays low so the seams between the four boxes are not drawn.
    """
    a, b = 8 - r, 8 + r
    inset = max(1.0, r * 0.62)
    c, d = 8 - r + inset, 8 + r - inset
    core = r * 0.78
    return [
        Box([8 - core, 8 - core, 8 - core], [8 + core, 8 + core, 8 + core],
            colour, material, ao=0.25),
        Box([a, c, c], [b, d, d], colour, material, ao=0.25),
        Box([c, a, c], [d, b, d], colour, material, ao=0.25),
        Box([c, c, a], [d, d, b], colour, material, ao=0.25),
    ]


def snitch(gold="#d9b23a", wing="#ced4de"):
    return ball(gold, 3, "gold") + [
        Box([0.5, 7, 7.5], [5, 9, 8.5], wing, "feather", rot=("z", 22.5, [5, 8, 8])),
        Box([11, 7, 7.5], [15.5, 9, 8.5], wing, "feather", rot=("z", -22.5, [11, 8, 8])),
    ]


def egg(metal, seam="#8f6b2a"):
    return [
        Box([5, 2, 5], [11, 12, 11], metal, "gold"),
        Box([4, 4, 4], [12, 10, 12], metal, "gold"),
        Box([6, 12, 6], [10, 14, 10], metal, "gold"),
        Box([3.8, 6.6, 3.8], [12.2, 7.4, 12.2], seam, "metal"),
    ]


def bat(wood="#8a6b3a", grip="#6b4a2f"):
    return [
        Box([7, 8, 7], [9, 15.5, 9], wood, "wood"),
        Box([7.25, 4, 7.25], [8.75, 8, 8.75], wood, "wood"),
        Box([7, 1, 7], [9, 4, 9], grip, "leather"),
        Box([6.7, 0.4, 6.7], [9.3, 1.2, 9.3], grip, "leather"),
    ]


def sword(blade="#c9cdd6", guard="#c6a64a", grip="#6e4a30", pommel="#a82826"):
    return [
        Box([7.25, 6, 7.5], [8.75, 15, 8.5], blade, "metal"),
        Box([7.5, 15, 7.6], [8.5, 16, 8.4], blade, "metal"),
        Box([4.5, 5, 7.2], [11.5, 6, 8.8], guard, "gold"),
        Box([7.25, 1.5, 7.4], [8.75, 5, 8.6], grip, "leather"),
        Box([6.9, 0.4, 7.1], [9.1, 1.5, 8.9], pommel, "gem"),
    ]


def goblet(metal, material="metal"):
    return [
        Box([5, 0.5, 5], [11, 1.5, 11], metal, material),
        Box([7, 1.5, 7], [9, 6, 9], metal, material),
        Box([4.5, 6, 4.5], [11.5, 12.5, 11.5], metal, material),
        Box([5, 12.5, 5], [11, 13.5, 11], metal, material),
    ]


def trophy(metal):
    """A goblet with two handles: a cup you win rather than one you drink from."""
    return goblet(metal, "gold") + [
        Box([2.8, 7.5, 7], [4.5, 11.5, 9], metal, "gold"),
        Box([11.5, 7.5, 7], [13.2, 11.5, 9], metal, "gold"),
    ]




def hat(cloth, band=None, brim=13, peak=15.5):
    """Brim, crown, and a point flopped right over at 45 degrees.

    Every concentric step is a horizontal ledge, and the eye reads a run of ledges as stairs
    — so the cure is not smaller steps but *fewer* of them. Three boxes: the brim, one tall
    crown, and a point thrown far enough off-axis that the outline is a hook rather than a
    staircase. Leaning only the tip while the crown still stepped twice fixed nothing.
    """
    x0 = (16 - brim) / 2
    boxes = [
        Box([x0, 1, x0], [16 - x0, 2.5, 16 - x0], cloth, "cloth"),
        Box([5, 2.5, 5], [11, 10, 11], cloth, "cloth", ao=0.5),
        Box([6.2, 9, 6.2], [9.8, peak, 9.8], cloth, "cloth", ao=0.5,
            rot=("z", 45, [8, 9.5, 8])),
    ]
    if band:
        boxes.append(Box([4.8, 2.6, 4.8], [11.2, 4.4, 11.2], band, "cloth"))
    return boxes


def telescope(brass, leather):
    """Three draws of decreasing girth, so it reads as something that collapses."""
    return [
        Box([6.5, 1, 6.5], [9.5, 6, 9.5], brass, "gold"),
        Box([7, 6, 7], [9, 11, 9], leather, "leather"),
        Box([7.25, 11, 7.25], [8.75, 15, 8.75], brass, "gold"),
        Box([6.2, 0.4, 6.2], [9.8, 1.4, 9.8], brass, "gold"),
    ]


def binoculars(body, lens):
    return [
        Box([3, 5, 6], [7, 12, 10], body, "leather"),
        Box([9, 5, 6], [13, 12, 10], body, "leather"),
        Box([7, 7, 7], [9, 10, 9], body, "metal"),
        Box([3.4, 11.9, 6.4], [6.6, 12.9, 9.6], lens, "glass"),
        Box([9.4, 11.9, 6.4], [12.6, 12.9, 9.6], lens, "glass"),
    ]


def quill(plume, nib="#3a3630"):
    return tilt([
        Box([7.5, 1, 7.5], [8.5, 4.5, 8.5], nib, "metal"),
        Box([7.4, 4.5, 7.4], [8.6, 8, 8.6], plume, "solid"),
        Box([6.6, 7.5, 7.5], [9.4, 11, 8.5], plume, "feather"),
        Box([6.9, 10.5, 7.5], [9.1, 14.5, 8.5], plume, "feather"),
    ], "z", 22.5)









def gem(colour):
    """Three boxes turned 45 degrees on Y, stepping in to a table.

    Two things were making a cut stone look like rubble. Five steps is too many — each one is
    another ledge, and the stack turns into a pinecone. And a box shows the viewer a *corner*
    at the GUI angle, which is the least gem-like thing it can do; turning every box 45
    degrees presents flat faces instead, so the silhouette is a diamond and the facets have
    somewhere to sit.
    """
    pivot = [8, 8, 8]
    return [
        Box([5.5, 2.5, 5.5], [10.5, 7, 10.5], colour, "gem", ao=0.3, rot=("y", 45, pivot)),
        Box([4.5, 7, 4.5], [11.5, 9.5, 11.5], colour, "gem", ao=0.3, rot=("y", 45, pivot)),
        Box([6, 9.5, 6], [10, 12.5, 10], colour, "gem", ao=0.3, rot=("y", 45, pivot)),
    ]


def ring(metal, stone):
    """A thick band under a stone, turned so you can see through it.

    A ring is only legible when the hole is. The GUI transform already turns the model 225
    degrees, which leaves an axis-aligned band at 45 degrees to the camera — half a hole.
    Turning it a further -45 brings the face square on; +45 takes it to 90 and the ring
    disappears into a sliver, which is the sign error worth remembering here.
    """
    pivot = [8, 8, 8]
    return [
        Box([4.5, 2.5, 6.5], [11.5, 4.5, 9.5], metal, "gold", rot=("y", -45, pivot)),
        Box([4.5, 9.5, 6.5], [11.5, 11.5, 9.5], metal, "gold", rot=("y", -45, pivot)),
        Box([4.5, 4.5, 6.5], [6.5, 9.5, 9.5], metal, "gold", rot=("y", -45, pivot)),
        Box([9.5, 4.5, 6.5], [11.5, 9.5, 9.5], metal, "gold", rot=("y", -45, pivot)),
        Box([5.5, 11, 5.8], [10.5, 14.5, 10.2], stone, "gem", ao=0.4, rot=("y", -45, pivot)),
    ]


def locket(metal, stone, chain="#8a8a96"):
    return [
        Box([4, 11, 7.5], [12, 12, 8.5], chain, "metal"),
        Box([4, 8, 7.5], [5, 11, 8.5], chain, "metal"),
        Box([11, 8, 7.5], [12, 11, 8.5], chain, "metal"),
        Box([5.5, 3, 7], [10.5, 9, 9], metal, "gold"),
        Box([6.8, 4.8, 6.6], [9.2, 7.2, 9.4], stone, "gem"),
    ]




def necklace(chain, bead):
    """A pendant on a short loop.

    A full collar is four one-unit bars, and a one-unit bar at this scale is a scratch, not a
    chain — the earlier cut read as a wire coat hanger. Cropping the chain to a loop and
    giving the stone most of the height puts the silhouette on the part worth looking at.
    """
    return [
        Box([5.5, 12, 7.3], [10.5, 13.2, 8.7], chain, "metal"),
        Box([5.5, 9.5, 7.3], [6.8, 12, 8.7], chain, "metal"),
        Box([9.2, 9.5, 7.3], [10.5, 12, 8.7], chain, "metal"),
        Box([6.8, 9.5, 7.4], [9.2, 10.8, 8.6], chain, "metal", ao=0.5),
        Box([4.5, 2, 5.8], [11.5, 9.8, 10.2], bead, "gem", ao=0.35),
    ]


def diadem(metal, stone):
    """A tiara: a band that rises to a peak, carrying one big stone at the centre."""
    return [
        Box([2.5, 4, 6.8], [13.5, 6, 9.2], metal, "gold"),
        Box([2.5, 6, 6.8], [4.5, 9, 9.2], metal, "gold"),
        Box([11.5, 6, 6.8], [13.5, 9, 9.2], metal, "gold"),
        Box([5, 6, 6.9], [11, 9.5, 9.1], metal, "gold", ao=0.5),
        Box([6, 9, 6.2], [10, 13.5, 9.8], stone, "gem", ao=0.4),
    ]


def hourglass(metal, sand, glass="#d8d2c0"):
    return [
        Box([4, 2, 6.5], [12, 3, 9.5], metal, "gold"),
        Box([4, 13, 6.5], [12, 14, 9.5], metal, "gold"),
        Box([4, 3, 6.5], [5, 13, 9.5], metal, "gold"),
        Box([11, 3, 6.5], [12, 13, 9.5], metal, "gold"),
        Box([6, 3.4, 6.6], [10, 7.4, 9.4], sand, "liquid"),
        Box([7.2, 7.4, 7.4], [8.8, 8.6, 8.6], sand, "liquid"),
        Box([6, 8.6, 6.6], [10, 12.6, 9.4], glass, "glass"),
    ]



def orb(glass, core):
    """A glass sphere with a band of colour caught round its equator.

    The core cannot simply sit inside the shell — buried geometry renders as nothing. It has
    to be wider than the sphere's own core cube to show at all, so it reads as a band rather
    than as a mist, which is the honest thing a cuboid can do here.
    """
    return ball(glass, 5, "glass") + [
        Box([3.2, 6.6, 3.2], [12.8, 9.4, 12.8], core, "glow", ao=0.3),
    ]


def mirror(frame, glass, handle=True, tall=False):
    y0, y1 = (2, 15) if tall else (6, 14)
    boxes = [
        Box([4, y0 + 1, 7], [12, y1 - 1, 7.8], glass, "glass"),
        Box([3, y0, 6.8], [13, y0 + 1, 8.4], frame, "gold"),
        Box([3, y1 - 1, 6.8], [13, y1, 8.4], frame, "gold"),
        Box([3, y0 + 1, 6.8], [4, y1 - 1, 8.4], frame, "gold"),
        Box([12, y0 + 1, 6.8], [13, y1 - 1, 8.4], frame, "gold"),
    ]
    if handle:
        boxes.append(Box([7, 1, 7], [9, y0 + 0.5, 8.2], frame, "gold"))
    return boxes


def basin(stone, water):
    """Four walls rather than a hollowed cube, so you can see down into it."""
    return [
        Box([4, 0.5, 4], [12, 2, 12], stone, "stone"),
        Box([3, 2, 3], [13, 4, 13], stone, "stone"),
        Box([2.5, 4, 2.5], [13.5, 9, 4], stone, "stone"),
        Box([2.5, 4, 12], [13.5, 9, 13.5], stone, "stone"),
        Box([2.5, 4, 4], [4, 9, 12], stone, "stone"),
        Box([12, 4, 4], [13.5, 9, 12], stone, "stone"),
        Box([4, 6.5, 4], [12, 7.5, 12], water, "glow"),
    ]


def cauldron(metal, brew=None):
    boxes = [
        Box([5, 0.5, 5], [11, 1.5, 11], metal, "metal"),
        Box([3, 1.5, 3], [13, 3, 13], metal, "metal"),
        Box([2.5, 3, 2.5], [13.5, 11, 4], metal, "metal"),
        Box([2.5, 3, 12], [13.5, 11, 13.5], metal, "metal"),
        Box([2.5, 3, 4], [4, 11, 12], metal, "metal"),
        Box([12, 3, 4], [13.5, 11, 12], metal, "metal"),
    ]
    if brew:
        boxes.append(Box([4, 8, 4], [12, 9, 12], brew, "liquid"))
    return boxes


def crate(body, lid, material="wood", clasp="#c6a64a"):
    return [
        Box([2.5, 1, 4], [13.5, 8, 12], body, material),
        Box([2, 8, 3.5], [14, 11, 12.5], lid, material),
        Box([7, 6.5, 3.4], [9, 9, 3.9], clasp, "gold"),
    ]


def beanbox(body, lid):
    return [
        Box([4.5, 1, 5.5], [11.5, 10, 10.5], body, "paper"),
        Box([4.2, 10, 5.2], [11.8, 12, 10.8], lid, "paper"),
        Box([5.5, 12, 6.5], [10.5, 13, 9.5], lid, "paper"),
    ]


def pouch(cloth, cord="#8f7a4a"):
    return [
        Box([4, 1.5, 4], [12, 9, 12], cloth, "cloth"),
        Box([5, 9, 5], [11, 11.5, 11], cloth, "cloth"),
        Box([4.7, 10.4, 4.7], [11.3, 11.6, 11.3], cord, "cloth"),
        Box([6.5, 11.5, 6.5], [9.5, 13.5, 9.5], cloth, "cloth"),
    ]


def sac(colour, tie="#8f7a4a"):
    return ball(colour, 5, "candy") + [
        Box([6.5, 12.4, 6.5], [9.5, 14.5, 9.5], tie, "cloth"),
    ]




def glove(colour):
    """A glove lying flat on its back, fingers splayed, thumb out to the side.

    Stood upright it is a cuff box under a palm box under a finger box — three concentric
    slabs, which is a plinth. Laid down, the fingers and thumb spread across the ground plane
    instead of stacking, and the GUI's three-quarter view reads the whole hand at once.
    """
    return [
        Box([2.5, 2, 5.5], [7, 5.5, 10.5], colour, "leather"),               # cuff
        Box([6.5, 2, 4.5], [12, 5.5, 11.5], colour, "leather", ao=0.6),      # palm
        Box([7.5, 2.2, 1.8], [10.5, 5, 4.5], colour, "leather", ao=0.5,
            rot=("y", 22.5, [9, 4, 4.5])),                                    # thumb
        Box([11.5, 2.2, 5], [14.5, 5.2, 7.6], colour, "leather", ao=0.5),
        Box([11.5, 2.2, 8.4], [14.5, 5.2, 11], colour, "leather", ao=0.5),
    ]


def cloth_fold(colour, trim=None):
    """A slab, a roll laid across it at an angle, and a corner hanging over the edge.

    Stacked layers read as tiers however you order or offset them, because the eye reads the
    repeated horizontal edges as steps. A *rolled* bolt lying across the pile at 22.5 degrees
    and a flap breaking the front edge give it the two things a cake never has: a diagonal,
    and an outline that is not closed.
    """
    boxes = [
        Box([2.5, 2, 3.5], [13.5, 6, 12.5], colour, "cloth"),
        Box([2, 6, 5], [14, 10, 9.5], colour, "cloth", ao=0.6,
            rot=("y", 22.5, [8, 8, 8])),                     # the bolt, laid across
        Box([4.5, 5.5, 2.2], [10, 9, 4.2], colour, "cloth", ao=0.6,
            rot=("x", -22.5, [8, 7, 4])),                    # a corner hanging over the front
    ]
    if trim:
        boxes.append(Box([2.4, 5.4, 3.4], [13.6, 6.3, 12.6], trim, "cloth"))
    return boxes


def radio(wood, dial="#c6a64a", mesh="#3a3630"):
    return [
        Box([2.5, 1.5, 4], [13.5, 12, 11.5], wood, "wood"),
        Box([4, 5.5, 3.5], [10, 10.5, 4.1], mesh, "cloth"),
        Box([10.5, 6.5, 3.5], [12.5, 8.5, 4.2], dial, "gold"),
        Box([5, 2.5, 3.5], [11, 4, 4.1], dial, "gold"),
        Box([11.8, 12, 7.2], [12.8, 15.5, 8.2], dial, "metal"),
    ]


def scales(brass, pan=None):
    """One pan hangs lower than the other, which is the whole point of a balance."""
    pan = pan or brass
    return [
        Box([5, 0.5, 5], [11, 2, 11], brass, "gold"),
        Box([7.25, 2, 7.25], [8.75, 11, 8.75], brass, "gold"),
        Box([2.5, 11, 7], [13.5, 12, 9], brass, "gold"),
        Box([2, 8, 6.5], [5.5, 8.8, 9.5], pan, "gold"),
        Box([10.5, 6.5, 6.5], [14, 7.3, 9.5], pan, "gold"),
        Box([3.5, 8.8, 7.8], [4.2, 11, 8.2], brass, "metal"),
        Box([11.9, 7.3, 7.8], [12.6, 11, 8.2], brass, "metal"),
    ]


def chess(light, dark):
    return [
        Box([2, 1, 2], [14, 2.5, 14], light, "wood"),
        Box([2.2, 2.5, 2.2], [7.9, 3, 7.9], dark, "stone"),
        Box([8.1, 2.5, 8.1], [13.8, 3, 13.8], dark, "stone"),
        Box([4, 3, 4], [6, 8, 6], light, "stone"),
        Box([10, 3, 10], [12, 7, 12], dark, "stone"),
    ]


def cards(face_colour, back="#c9c2a8"):
    """A fanned stack: three cards offset enough that you can count them."""
    return [
        Box([4, 2, 5], [12, 3.5, 11], back, "paper"),
        Box([3.4, 3.5, 4.6], [11.4, 5, 10.6], back, "paper"),
        Box([4.6, 5, 5.4], [12.6, 6.5, 11.4], face_colour, "print"),
    ]


def device(body, glass="#8fd6c2"):
    return [
        Box([5, 1, 5], [11, 3, 11], body, "metal"),
        Box([6.5, 3, 6.5], [9.5, 8, 9.5], body, "metal"),
        Box([4.5, 8, 4.5], [11.5, 12, 11.5], glass, "glass"),
        Box([4.2, 12, 4.2], [11.8, 13, 11.8], body, "gold"),
    ]


def rod(metal, tip):
    return tilt([
        Box([7.25, 1, 7.25], [8.75, 10, 8.75], metal, "metal"),
        Box([6.75, 10, 6.75], [9.25, 12, 9.25], metal, "gold"),
        Box([7, 12, 7], [9, 14.5, 9], tip, "glow"),
    ], "z", 22.5)


def coin(metal):
    return [
        Box([4, 4, 7.4], [12, 12, 8.6], metal, "gold"),
        Box([5, 3, 7.5], [11, 13, 8.5], metal, "gold"),
        Box([3, 5, 7.5], [13, 11, 8.5], metal, "gold"),
    ]


def bar(wrapper, inner):
    return [
        Box([3, 3, 6.5], [13, 13, 9.5], inner, "candy"),
        Box([2.8, 5, 6.3], [13.2, 11, 9.7], wrapper, "paper"),
    ]


def tape(colour, core="#d8d2c0"):
    """Four arcs of a roll plus the reel inside it, which is as close to a torus as
    axis-aligned cuboids get."""
    return [
        Box([4, 3, 6.5], [12, 5, 9.5], colour, "paper"),
        Box([4, 11, 6.5], [12, 13, 9.5], colour, "paper"),
        Box([3, 5, 6.5], [5, 11, 9.5], colour, "paper"),
        Box([11, 5, 6.5], [13, 11, 9.5], colour, "paper"),
        Box([5, 5, 7], [11, 11, 9], core, "paper"),
    ]


def flame(colour, base="#6b6b72"):
    return [
        Box([5, 1, 5], [11, 3, 11], base, "metal"),
        Box([6, 3, 6], [10, 8, 10], colour, "glow"),
        Box([6.5, 8, 6.5], [9.5, 12, 9.5], colour, "glow"),
        Box([7, 12, 7], [9, 15, 9], colour, "glow"),
    ]


def firework(body, fuse="#c6a64a"):
    return [
        Box([6, 1, 6], [10, 11, 10], body, "paper"),
        Box([6.5, 11, 6.5], [9.5, 13, 9.5], body, "paper"),
        Box([7.4, 13, 7.4], [8.6, 15.5, 8.6], fuse, "solid"),
        Box([5.5, 3, 5.5], [10.5, 4.5, 10.5], fuse, "gold"),
    ]


def sweet(colour, wrapper=None):
    """A boiled sweet, and if it has a wrapper, the twist at each end."""
    boxes = ball(colour, 3.5, "candy")
    if wrapper:
        boxes += [
            Box([2.2, 7, 7], [5, 9, 9], wrapper, "paper"),
            Box([11, 7, 7], [13.8, 9, 9], wrapper, "paper"),
        ]
    return boxes


# Ten sweets that are all `sweet()` in a different colour are not ten sweets — the same trap
# `canon_sprites.py` calls out for books. Confectionery comes in shapes, so these are shapes.

def fudge(colour):
    """Cut fudge: two squares off the slab, one sitting askew on the other."""
    return [
        Box([3.5, 2, 4.5], [11.5, 6, 12.5], colour, "candy", ao=0.7),
        Box([5, 6, 3.5], [13, 10, 11.5], colour, "candy", ao=0.7,
            rot=("y", 22.5, [8, 8, 8])),
    ]


def nougat(colour, topping=None):
    """A cut bar, long and low, with a band of something across the top."""
    boxes = [Box([2, 3, 5.5], [14, 8, 10.5], colour, "candy", ao=0.7)]
    if topping:
        boxes.append(Box([2.2, 8, 5.8], [13.8, 9.6, 10.2], topping, "candy", ao=0.5))
    return boxes


def toffee(colour, wrapper):
    """Wrapped toffee: a long lozenge with the paper twisted off both ends."""
    return [
        Box([4.5, 5.5, 5.5], [11.5, 10.5, 10.5], colour, "candy", ao=0.6),
        Box([3.5, 6.5, 6.5], [4.5, 9.5, 9.5], colour, "candy", ao=0.6),
        Box([11.5, 6.5, 6.5], [12.5, 9.5, 9.5], colour, "candy", ao=0.6),
        Box([1, 6.6, 6.6], [3.5, 9.4, 9.4], wrapper, "paper",
            rot=("z", 22.5, [3.5, 8, 8])),
        Box([12.5, 6.6, 6.6], [15, 9.4, 9.4], wrapper, "paper",
            rot=("z", 22.5, [12.5, 8, 8])),
    ]


def pastille(colour):
    """A flat lozenge, and a second one leaning on it so the stack is legible."""
    return [
        Box([3.5, 2, 4], [12.5, 4.5, 13], colour, "candy", ao=0.7),
        Box([4.5, 4.5, 3], [12, 7, 11.5], colour, "candy", ao=0.7,
            rot=("z", 22.5, [8, 5, 8])),
    ]


def capsule(colour, cap=None):
    """A pill: two halves, the darker one capping the lighter."""
    return [
        Box([5, 4, 5], [11, 8, 11], colour, "candy", ao=0.6),
        Box([4.7, 7.8, 4.7], [11.3, 11.5, 11.3], cap or colour, "candy", ao=0.6),
    ]


def whizzbee(colour, wing="#e8e4d2"):
    """A sherbet bee: a striped round body with a pair of wings out to the side."""
    return ball(colour, 3.5, "candy") + [
        # Proud of the sphere on purpose: sunk flush it sits inside the core cube and the
        # bee loses its stripe entirely.
        Box([4.9, 6.5, 4.9], [11.1, 9.5, 11.1], "#4a4034", "candy", ao=0.4),
        Box([1.5, 9, 7.4], [5.5, 10, 8.6], wing, "feather",
            rot=("z", 22.5, [5.5, 9.5, 8])),
        Box([10.5, 9, 7.4], [14.5, 10, 8.6], wing, "feather",
            rot=("z", -22.5, [10.5, 9.5, 8])),
    ]


def toad(colour):
    """A peppermint toad: a squat body, two eye bumps and folded back legs."""
    return [
        Box([4, 3, 4.5], [12, 7.5, 11.5], colour, "candy", ao=0.6),
        Box([5.5, 7.5, 5.5], [10.5, 9.5, 10.5], colour, "candy", ao=0.6),
        Box([5.8, 9.5, 6], [7.4, 11, 7.6], colour, "candy", ao=0.5),
        Box([8.6, 9.5, 6], [10.2, 11, 7.6], colour, "candy", ao=0.5),
        Box([2.8, 3.2, 6], [4, 6.5, 10], colour, "candy", ao=0.5),
        Box([12, 3.2, 6], [13.2, 6.5, 10], colour, "candy", ao=0.5),
    ]


def gumpack(colour, gum):
    """A paper sleeve with the sticks of gum showing at one end."""
    return [
        Box([4, 2, 5.5], [12, 11, 10.5], colour, "paper"),
        Box([4.4, 11, 5.9], [11.6, 13.5, 10.1], gum, "candy", ao=0.6),
        Box([3.8, 5.5, 5.3], [12.2, 7.5, 10.7], gum, "paper", ao=0.5),
    ]


def tart(crust, filling):
    return [
        Box([3, 1, 3], [13, 3, 13], crust, "solid"),
        Box([2.5, 3, 2.5], [13.5, 5, 13.5], crust, "solid"),
        Box([4, 5, 4], [12, 5.8, 12], filling, "candy"),
    ]


def pasty(crust, crimp=None):
    return [
        Box([3, 3, 5], [13, 9, 11], crust, "solid"),
        Box([4, 9, 6], [12, 10.5, 10], crust, "solid"),
        Box([5.5, 10.5, 6.5], [10.5, 11.5, 9.5], crimp or crust, "solid"),
    ]


def plum(colour, stem="#6b7a3a"):
    return ball(colour, 4, "candy") + [
        Box([7.4, 12, 7.4], [8.6, 15, 8.6], stem, "wood"),
        Box([8.6, 13.4, 7.6], [11, 14.4, 8.4], stem, "cloth"),
    ]





def hand_of_glory(skin, flame_colour="#e0a83a"):
    """Three fat fingers off a broad palm, and a flame that reads at a glance.

    Five slim fingers is anatomically nearer and visually mush: below about two units wide a
    finger is one texel of silhouette and disappears.
    """
    return [
        Box([6, 1, 7], [10, 5, 9], skin, "leather"),
        Box([4, 5, 6], [12, 10.5, 10], skin, "leather", ao=0.6),
        Box([4.4, 10.5, 6.4], [6.8, 13, 9.6], skin, "leather", ao=0.5),
        Box([7.1, 10.5, 6.4], [9.5, 14, 9.6], skin, "leather", ao=0.5),
        Box([9.8, 10.5, 6.4], [12, 12.5, 9.6], skin, "leather", ao=0.5),
        Box([6.6, 14, 6.9], [10, 16, 9.1], flame_colour, "glow", ao=0.2),
    ]


def shrunken_head(skin, hair):
    return [
        Box([4.5, 4, 4.5], [11.5, 11, 11.5], skin, "leather"),
        Box([4, 10, 4], [12, 13, 12], hair, "fur"),
        Box([5.5, 11, 3.6], [10.5, 14.5, 5], hair, "fur"),
        Box([6, 2, 6], [10, 4, 10], skin, "leather"),
    ]


def cabinet(wood, brass="#b08a2e"):
    return [
        Box([3, 0.5, 4.5], [13, 15, 11.5], wood, "wood"),
        Box([3.2, 1.5, 4.1], [7.8, 13.5, 4.6], wood, "wood"),
        Box([8.2, 1.5, 4.1], [12.8, 13.5, 4.6], wood, "wood"),
        Box([7.4, 7, 3.8], [8.6, 8.5, 4.2], brass, "gold"),
        Box([2.5, 15, 4], [13.5, 16, 12], wood, "wood"),
    ]


# --------------------------------------------------------------------------- catalogue
#
# Base colours are taken from the sprite tables in `item_icons.py` and `canon_sprites.py`,
# so the model in your hand and the icon in the hotbar are the same object. Where a shape
# needs a second or third colour the sprite never had — a cork, a clasp, a lens — it is
# chosen here.
#
# Deliberately absent:
#   ingredients           hairs, feathers, cores, claws, a fang, a horn, a spine, gillyweed,
#                         the bezoar, the twig bundle. Raw crafting and brewing material you
#                         read off a list, not props you hold up and look at, so the flat
#                         sprite is the right call and a cuboid is just more to render.
#   chocolate_frog        owned by another pass; leaving it flat avoids two tools fighting
#   famous_wizard_card    tools/wizard_cards.py already gives it a real cuboid card
#   demiguise_hair        its items/ definition range-dispatches over five fade models, so
#                         modelling the base alone would pop from 3D to flat mid-use
#   wand, brooms, coins   already have hand-authored or GeckoLib models
#   trunks, Newt's case   block items; their models come from block-model generation
#   armour, spawn eggs    flat sprites on purpose

# --------------------------------------------------------------------------- hold classes
#
# Which way a prop is held follows from what it is, and what it is follows from the builder that
# shaped it: every vial is held like a vial. So the class is attached to the builder, once, and
# travels with the box list it returns -- no per-item table to keep in step with ITEMS.

HOLD_BY_BUILDER = {
    "vessel": ("bottle", "vial", "flask"),
    "book": ("book", "newspaper", "envelope"),
    "rod": ("quill", "telescope", "rod", "bat", "sword", "firework"),
    "small": ("ball", "gem", "coin", "bar", "pastille", "sweet", "fudge", "nougat", "toffee",
              "capsule", "toad", "whizzbee", "plum", "tart", "pasty", "egg", "ring", "tape", "sac",
              "shrunken_head", "cards", "gumpack", "beanbox", "snitch"),
    "object": ("crate", "cauldron", "radio", "scales", "chess", "basin", "binoculars", "device",
               "glove", "cloth_fold", "hat", "pouch", "cabinet", "flame", "scroll", "mirror"),
    "artifact": ("locket", "diadem", "necklace", "trophy", "goblet", "hand_of_glory", "orb",
                 "hourglass"),
}
DEFAULT_HOLD = "object"


class Held(list):
    """A builder's box list, carrying the hold class of the builder that made it."""
    hold = DEFAULT_HOLD


def _held_by(builder, hold):
    def build_held(*args, **kwargs):
        boxes = Held(builder(*args, **kwargs))
        boxes.hold = hold
        return boxes
    build_held.__name__ = builder.__name__
    build_held.__doc__ = builder.__doc__
    return build_held


for _hold, _names in HOLD_BY_BUILDER.items():
    for _name in _names:
        globals()[_name] = _held_by(globals()[_name], _hold)


def hold_of(boxes):
    return getattr(boxes, "hold", DEFAULT_HOLD)


ITEMS = {
    # --- drink, brews and essences ----------------------------------------
    "butterbeer": bottle("#c98a2b", "#e0a850"),
    "firewhisky": bottle("#8f3a1d", "#d4581f"),
    "pumpkin_juice": bottle("#a85f24", "#e08a2b"),
    # The one tinted item: `brew` is a single item standing in for the whole catalogue, and
    # what is in the bottle is only known from its brew_id component at render time.
    # Everything else here is one fixed drink and keeps its painted colour.
    "brew": vial("#6b5aa8", "#8f6bd6", tint=True),
    "dittany": vial("#4a8f6b", "#6bc294"),
    "blood_pact_vial": vial("#7a1d24", "#b02531"),
    "broom_polish": vial("#8f7040", "#c2a05a"),
    "ink_bottle": vial("#2b2f42", "#25283a"),
    "elixir_of_life": vial("#c9a83a", "#e8c25a"),
    "acromantula_venom": vial("#5a7a2a", "#7fa83a"),
    "essence_of_dittany": flask("#4a8f6b", "#7ac69a"),
    "murtlap_essence": flask("#8f7a2a", "#c6a83a"),
    "draught_of_peace": vial("#6b8fb4", "#8fb4d6"),
    "blood_replenishing_potion": vial("#6b1a1e", "#8a1e22"),
    "memory_vial": vial("#9aaab8", "#c6d6e4"),
    "mrs_skowers_mess_remover": bottle("#5a8f9a", "#7ab4c6"),
    "flesh_eating_slug_repellent": bottle("#4a5a2a", "#6b7a3a"),
    "ghoul_slime": vial("#7a8a6b", "#6b8a5a"),
    "matagot_essence": vial("#3a3a44", "#5a5a6b"),
    "hidebehind_shadow_essence": vial("#2b2438", "#3a3048", liquid_style="dark"),
    "pukwudgie_venom_sac": sac("#7aa83a"),
    "portable_swamp": sac("#4a6b3a"),

    # --- books -------------------------------------------------------------
    "a_history_of_magic": book("#7a3a2b"),
    "riddles_diary": book("#2b2f4a", w=9, h=12),
    "ministry_handbook": book("#3a4a6b"),
    "bestiary": book("#5a3a22", clasp="#c6a64a", w=11, h=13),
    "hogwarts_a_history": book("#7a2f3a", w=11, h=14),
    "rise_and_fall_of_the_dark_arts": book("#3a3040", clasp="#8a8a96", w=10, h=14),
    "tales_of_beedle_the_bard": book("#6e4a2c", clasp="#c6a64a", w=10, h=13),
    "secrets_of_the_darkest_art": book("#3e3040", clasp="#6b6b72", w=9, h=14),
    "moste_potente_potions": book("#3e4a38", w=11, h=12),
    "standard_book_of_spells": book("#3a5a8a", w=10, h=13),
    "monster_book_of_monsters": book("#5e3a22", clasp="#8a6b3a", w=11, h=12, thick=2.0),
    "advanced_potion_making": book("#4a6b5a", w=9, h=14),
    "magical_draughts_and_potions": book("#3a6b6e", w=10, h=12),
    "fantastic_beasts_and_where_to_find_them": book("#7a6b3a", w=11, h=13),
    "quidditch_through_the_ages": book("#8a5a2e", w=10, h=12),
    "one_thousand_magical_herbs_and_fungi": book("#4a6b34", w=10, h=13),
    "beginners_guide_to_transfiguration": book("#5a4a7a", w=9, h=13),
    "unfogging_the_future": book("#7a4a6b", w=10, h=12),

    # --- paper -------------------------------------------------------------
    "parchment": scroll("#dcd2b4", "#8f2f3a"),
    "daily_prophet": newspaper("#b8b2a0"),
    "the_quibbler": newspaper("#c6b884"),
    "howler": envelope("#b3241d"),
    "exploding_snap": cards("#b3241d"),
    "spellotape": tape("#c2a86e"),

    # --- artefacts ----------------------------------------------------------
    "philosophers_stone": gem("#c9302b"),
    "resurrection_stone": gem("#3a3a44"),
    "horned_serpent_gem": gem("#d6c25a"),
    "marvolo_gaunts_ring": ring("#c2a03a", "#3a3a44"),
    "slytherins_locket": locket("#c2a03a", "#2f7a4a"),
    "hufflepuffs_cup": trophy("#d6b03a"),
    "ravenclaws_diadem": diadem("#c2a03a", "#5a93c2"),
    "opal_necklace": necklace("#c6d2e0", "#a8c6d6"),
    "time_turner": hourglass("#d6b03a", "#e8d8a8"),
    "remembrall": orb("#d6d6e0", "#c43a32"),
    "foe_glass": mirror("#7a8a9a", "#4a5a6b", handle=False),
    "two_way_mirror": mirror("#9aa8b5", "#c6d2e0"),
    "mirror_of_erised": mirror("#b08a2e", "#c6d2e0", handle=False, tall=True),
    "pensieve": basin("#8fa8c2", "#c6d6e4"),
    "hand_of_glory": hand_of_glory("#c2ad8f"),
    "dark_mark_brand": rod("#3a3540", "#7a3aa8"),
    "hermiones_beaded_bag": pouch("#8f5a7a", "#c2a03a"),
    "sword_of_gryffindor": sword(),
    "goblet_of_fire": goblet("#6b5228", "wood"),
    "triwizard_cup": trophy("#c2a03a"),
    "golden_egg": egg("#d9b23a"),
    "shrunken_head": shrunken_head("#6b4a32", "#2b2118"),
    "vanishing_cabinet": cabinet("#4a3626"),
    "gubraithian_fire": flame("#3ac6b4"),
    "da_galleon": coin("#c2a03a"),

    # --- school kit ---------------------------------------------------------
    "quill": quill("#e4deca"),
    "quick_quotes_quill": quill("#7ac63a"),
    "auto_answer_quill": quill("#c2a03a"),
    "telescope": telescope("#b08a2e", "#6e5a3a"),
    "punching_telescope": telescope("#c6a64a", "#8a6b3a"),
    "omnioculars": binoculars("#8f7a3a", "#8fd6c2"),
    "brass_scales": scales("#b08a2e"),
    "wizards_chess_set": chess("#d8d2c0", "#4a4034"),
    "gobstones": ball("#7a8a6e", 4, "stone"),
    "self_stirring_cauldron": cauldron("#4a4a52", "#7a5ac2"),
    "collapsible_cauldron": cauldron("#6b6b72"),
    "sorting_hat": hat("#8a6c4e", brim=13),
    "wizarding_wireless": radio("#7a5836"),

    # --- detection ----------------------------------------------------------
    "secrecy_sensor": device("#b0894a"),
    "probity_probe": rod("#c2a03a", "#e8d24a"),
    "revealer": bar("#e0d2b4", "#c43a32"),

    # --- quidditch ----------------------------------------------------------
    "golden_snitch": snitch(),
    "quaffle": ball("#b3241d", 5, "leather"),
    "bludger": ball("#3a3a42", 5, "metal"),
    "beaters_bat": bat(),
    "broomstick_servicing_kit": crate("#6b4a2e", "#3a2a1e"),

    # --- worn -------------------------------------------------------------
    "quidditch_robes": cloth_fold("#7a1e22", "#c6a64a"),
    "shield_cloak": cloth_fold("#3e5a78", "#8fb4d6"),
    "invisibility_cloak": cloth_fold("#c6cede", "#8fa8c2"),
    "deathly_hallow_cloak": cloth_fold("#b5c2d6", "#e0e6ee"),
    "dragon_hide_gloves": glove("#5a3a2e"),
    "shield_gloves": glove("#44607e"),
    "headless_hat": hat("#d66ea8", "#8a3a6b", brim=13),
    "shield_hat": hat("#4a6b8a", "#2f4a6b", brim=11),

    # --- sweets and joke shop ----------------------------------------------
    "bertie_botts_every_flavour_beans": beanbox("#c2a05a", "#8f5a7a"),
    "peppermint_toad": toad("#4a8f6b"),
    "fizzing_whizzbee": whizzbee("#c2a03a"),
    "droobles_best_blowing_gum": gumpack("#5a93d6", "#c6d2e0"),
    "puking_pastilles": pastille("#e07a2a"),
    "nosebleed_nougat": nougat("#e0d2b4", "#c4392e"),
    "fainting_fancies": pastille("#6e7ac6"),
    "fever_fudge": fudge("#c6853a"),
    "ton_tongue_toffee": toffee("#a8702e", "#d6c9a8"),
    "canary_cream": sweet("#e8d24a", "#e0d2b4"),
    "u_no_poo": capsule("#c9b48a", "#8a6b4a"),
    "chocolate_bar": bar("#8a7a5a", "#5a3a22"),
    "skiving_snackbox": crate("#c43a7a", "#e0a83a", material="paper"),
    "dungbomb": sac("#6b5a2e", "#8f7a4a"),
    "wildfire_whiz_bangs": firework("#e0562b"),
    "filibusters_fireworks": firework("#3a7ac6"),

    # --- food and plants ----------------------------------------------------
    "treacle_tart": tart("#c9a05a", "#d6a83a"),
    "pumpkin_pasty": pasty("#d6a84a"),
    "dirigible_plum": plum("#8f5ac2"),
}

# --------------------------------------------------------------------------- validation

def validate(item_id, boxes):
    """Catch the mistakes that produce a model which loads but shows nothing useful.

    A box outside the model bounds makes Minecraft reject the whole file, and a box wholly
    inside another is invisible geometry that still costs atlas — both are easy to write and
    impossible to see in the JSON.
    """
    problems = []
    for index, box in enumerate(boxes):
        for axis, name in enumerate("xyz"):
            lo, hi = box.frm[axis], box.to[axis]
            if hi <= lo:
                problems.append(f"box {index} has {name} from {lo} to {hi}")
            if lo < -16 or hi > 32:
                problems.append(f"box {index} {name} {lo}..{hi} is outside the -16..32 bounds")
    for a, box in enumerate(boxes):
        for b, other in enumerate(boxes):
            if a == b or box.rot != other.rot:
                continue
            if all(other.frm[k] <= box.frm[k] and box.to[k] <= other.to[k] for k in range(3)):
                problems.append(f"box {a} is entirely inside box {b} and will never be seen")
    if problems:
        raise SystemExit(f"{item_id}: " + "; ".join(problems))


# --------------------------------------------------------------------------- datagen seam
#
# `src/generated/resources` is a second resource root. An item modelled here must be
# declared custom in ModModelProvider, or datagen keeps emitting a flat stub into that root
# and which of the two the game loads comes down to the order processResources happens to
# copy them in. The Java file holds the list; this only checks the two agree, because a
# silent disagreement shows up as a wafer-flat item nobody can explain.

DECLARED_BLOCK = re.compile(
    r"HAND_MODELLED_CANON\s*=\s*Set\.of\((.*?)\);", re.S)
CANON_ID = re.compile(r'registerItem\(\s*"([a-z0-9_]+)"')


def read_ids(path, pattern, whole_file=True):
    if not os.path.exists(path):
        return None
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
    if whole_file:
        return set(pattern.findall(text))
    return set()


# --------------------------------------------------------------------------- flat items
#
# Items this tool deliberately does NOT model, because a cuboid is the wrong primitive for
# them and the flat sprite is the better picture.
#
# Extruding a sprite into boxes works for anything already boxy — books, bottles, crates,
# blades. It fails for round: a Quaffle becomes a red cube, a Bludger a black cube, a
# Remembrall a grey box with a red smear. Rendered side by side against the sprites they
# were built from, the sprite won on every one of these, and the sprites were sitting
# unused on disk the whole time because the model bound `<id>_3d.png` instead.
#
# They are listed rather than deleted from ITEMS so the reason survives: without this note
# the obvious "fix" is to model the missing ones, which is how they got cubed in the first
# place. `model_is_ours` treats a bare item/generated stub as overwritable — that is the
# whole point of this tool — so a flat model alone would not have survived the next run.
# Membership here is what protects it.
FLAT_ITEMS = {
    "bludger",
    "canary_cream",
    "dirigible_plum",
    "fizzing_whizzbee",
    "ghoul_slime",
    "goblet_of_fire",
    "gobstones",
    "golden_egg",
    "golden_snitch",
    "howler",
    "marvolo_gaunts_ring",
    "matagot_essence",
    "opal_necklace",
    "peppermint_toad",
    "philosophers_stone",
    "portable_swamp",
    "quaffle",
    "remembrall",
}


GEO_DIR = os.path.join(ASSETS, "geckolib", "models", "item")


def is_geo(item_id):
    """An AnimatedItem draws its GeckoLib model in hand (tools/item_geo.py); a cuboid here would
    never be seen, and its only job -- a display block -- is now the geo's own `<id>_held`."""
    return os.path.exists(os.path.join(GEO_DIR, item_id + ".geo.json"))


def check_datagen_seam(written):
    """Report canon stubs that this tool models but ModModelProvider still flat-generates."""
    canon = read_ids(CANON_REGISTRY, CANON_ID)
    if canon is None:
        return []
    declared = set()
    if os.path.exists(MODEL_PROVIDER):
        with open(MODEL_PROVIDER, encoding="utf-8") as fh:
            block = DECLARED_BLOCK.search(fh.read())
        if block:
            declared = set(re.findall(r'"([a-z0-9_]+)"', block.group(1)))
    modelled_canon = {i for i in ITEMS if i in canon and i not in FLAT_ITEMS and not is_geo(i)}
    return sorted(modelled_canon - declared), sorted(declared - modelled_canon)


# --------------------------------------------------------------------------- driver

def redisplay(only):
    """Recompute the display block of every model this tool wrote, and nothing else.

    Transforms are the part of these models that is tuned by looking at them in game; the
    geometry and the painted sheets are not. Keeping the two rewrites apart means a transform
    change never repaints a texture, and the diff shows exactly what moved.
    """
    changed = 0
    for item_id, boxes in sorted(ITEMS.items()):
        if (only and item_id not in only) or item_id in FLAT_ITEMS or is_geo(item_id):
            continue
        path = os.path.join(ITEM_MODEL_DIR, item_id + ".json")
        if not os.path.exists(path):
            continue
        model = item_display.load_json(path)
        if model.get("credit") != CREDIT:
            continue
        display = item_display.display_for(hold_of(boxes), item_display.cuboid_bounds(model["elements"]))
        if display != model.get("display"):
            model["display"] = display
            with open(path, "w", encoding="utf-8", newline="\n") as fh:
                json.dump(model, fh, indent=2)
                fh.write("\n")
            changed += 1
    print(f"display rewritten on {changed} models")
    return 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--force", action="store_true",
                    help="overwrite even hand-authored models and textures")
    ap.add_argument("--only", default="", help="comma-separated item ids")
    ap.add_argument("--list", action="store_true", help="print the catalogue and stop")
    ap.add_argument("--display-only", action="store_true",
                    help="rewrite only the display block of models this tool owns; "
                         "geometry and sheets are left byte-for-byte alone")
    args = ap.parse_args()
    only = {s.strip() for s in args.only.split(",") if s.strip()}

    if args.list:
        for item_id in sorted(ITEMS):
            print(f"{item_id:44s} {len(ITEMS[item_id])} boxes")
        print(f"\n{len(ITEMS)} items")
        return 0

    if args.display_only:
        return redisplay(only)

    unknown = only - set(ITEMS)
    if unknown:
        raise SystemExit(f"not in the catalogue: {', '.join(sorted(unknown))}")

    written, skipped, flat, geo = [], [], [], []
    for item_id, boxes in sorted(ITEMS.items()):
        if only and item_id not in only:
            continue
        if item_id in FLAT_ITEMS:
            flat.append(item_id)
            continue
        if is_geo(item_id):
            geo.append(item_id)
            continue
        validate(item_id, boxes)
        tex_path = os.path.join(ITEM_TEX_DIR, item_id + "_3d.png")
        model_path = os.path.join(ITEM_MODEL_DIR, item_id + ".json")
        # Guard the *model*, not just the texture. Checking only the texture meant a model
        # that did not exist yet counted as regenerable and the existing JSON was
        # overwritten sight unseen — which is how ten item models got clobbered on the
        # first run. They happened to be trivial item/generated stubs; the next one might
        # not be.
        if not args.force and not (is_regenerable(tex_path, MARKER) and model_is_ours(model_path)):
            skipped.append(item_id)
            continue
        img, model = build(item_id, boxes, hold_of(boxes))
        save(img, tex_path, MARKER)
        os.makedirs(ITEM_MODEL_DIR, exist_ok=True)
        with open(model_path, "w", encoding="utf-8", newline="\n") as fh:
            json.dump(model, fh, indent=2)
            fh.write("\n")
        written.append(item_id)

    print(f"built {len(written)} 3D item models")
    if flat:
        print(f"left flat on purpose ({len(flat)}): {', '.join(flat)}")
    if geo:
        print(f"drawn by GeckoLib instead ({len(geo)}): {', '.join(geo)}")
    if skipped:
        print(f"skipped {len(skipped)} hand-authored: {', '.join(skipped)}")

    undeclared, stale = check_datagen_seam(written)
    if undeclared:
        print("\nModModelProvider.HAND_MODELLED_CANON is missing these, so datagen will keep\n"
              "emitting a flat stub for them into src/generated/resources:")
        for item_id in undeclared:
            print(f'        "{item_id}",')
        return 1
    if stale:
        print("\nHAND_MODELLED_CANON names ids this tool does not model; they will render as\n"
              "the missing-model cube: " + ", ".join(stale))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
